### ISSUE TITLE
tooltip sorting is not working

### ISSUE THREAD

**Issue by briangann** [grafana/grafana-polystat-panel#107]
The primary and secondary sort options are not being applied to tooltips.

When you select any direction for any of the three field options, the tooltip remains the same (this applies to both primary and secondary sorting)

![image](https://user-images.githubusercontent.com/7364245/73310364-c9613d80-41e9-11ea-9b7a-5044944553c9.png)

![image](https://user-images.githubusercontent.com/7364245/73310376-d2520f00-41e9-11ea-8d5b-02dc56d8d4b0.png)

**Comment by xxtheatrainxx** [comment]
Has there been any update on this?

**Comment by briangann** [comment]
this should have been fixed in v1.1.0, will verify

**Comment by dnck** [comment]
commenting to put some momentum behind this issue
