### ISSUE TITLE
Panel plugin not found: grafana-polystat-panel

### ISSUE THREAD

**Issue by LarsLarsLars** [grafana/grafana-polystat-panel#115]
Hello!
Thanks for the plugin!
Our IT teams and C level folks are obsessed with it!  
However since the last week, we're noticing this error and we've been banging our heads on solving it.

Browser : Firefox, IE, Edge
Grafana Version : 6.1.6 (as a docker container)
Data Source : Prometheus
Polystat plugin version : v1.1.0

Error :
![image](https://user-images.githubusercontent.com/26286579/76323760-8354ca80-62bb-11ea-9eef-c7d5cba095bf.png)

Content of /var/lib/grafana/plugins :
![image](https://user-images.githubusercontent.com/26286579/76324132-f65e4100-62bb-11ea-8f85-5719fdcb9bc6.png)

Grafana JSON :

    {
      "colors": [
        "#299c46",
        "rgba(237, 129, 40, 0.89)",
        "#d44a3a"
      ],
      "datasource": "PrometheusDev",
      "gridPos": {
        "h": 3,
        "w": 9,
        "x": 9,
        "y": 0
      },
      "id": 46,
      "links": [],
      "polystat": {
        "animationSpeed": 2500,
        "columnAutoSize": true,
        "columns": "",
        "defaultClickThrough": "",
        "defaultClickThroughSanitize": true,
        "displayLimit": 500,
        "fontAutoScale": true,
        "fontSize": 12,
        "fontType": "Roboto",
        "globalDecimals": 0,
        "globalDisplayMode": "all",
        "globalDisplayTextTriggeredEmpty": "OK",
        "globalOperatorName": "current",
        "globalUnitFormat": "short",
        "gradientEnabled": true,
        "hexagonSortByDirection": "asc",
        "hexagonSortByField": "name",
        "maxMetrics": 0,
        "polygonBorderColor": "#052b51",
        "polygonBorderSize": 2,
        "polygonGlobalFillColor": "#f9e2d2",
        "radius": 20,
        "radiusAutoSize": false,
        "rowAutoSize": true,
        "rows": 5,
        "shape": "hexagon_pointed_top",
        "tooltipDisplayMode": "all",
        "tooltipDisplayTextTriggeredEmpty": "OK",
        "tooltipFontSize": 12,
        "tooltipFontType": "Roboto",
        "tooltipPrimarySortDirection": "desc",
        "tooltipPrimarySortField": "name",
        "tooltipSecondarySortDirection": "desc",
        "tooltipSecondarySortField": "value",
        "tooltipTimestampEnabled": false
      },
      "repeatDirection": "h",
      "savedComposites": [],
      "savedOverrides": [
        {
          "clickThrough": "",
          "colors": [
            "#299c46",
            "#e5ac0e",
            "#bf1b00",
            "#ffffff"
          ],
          "decimals": 0,
          "enabled": true,
          "label": "OVERRIDE 1",
          "metricName": "/.*/",
          "operatorName": "current",
          "prefix": "",
          "sanitizeURLEnabled": true,
          "scaledDecimals": null,
          "suffix": "",
          "thresholds": [
            {
              "color": "#bf1b00",
              "state": 2,
              "value": 0
            },
            {
              "color": "#299c46",
              "state": 0,
              "value": 1
            }
          ],
          "unitFormat": "short"
        }
      ],
      "targets": [
        {
          "expr": "max_over_time(probe_success{job=~\"(dsi|dev)-probe.*http.*prio2-.*production\"}[90s])",
          "format": "time_series",
          "interval": "",
          "intervalFactor": 1,
          "legendFormat": "{{instance}}",
          "refId": "A"
        }
      ],
      "title": "Probe http(s) prio2",
      "type": "grafana-polystat-panel"
    }
Could you help us on this issue?

**Comment by LarsLarsLars** [comment]
Also we tried :
- Manually installing the plugin from the .zip package.
- Automatic installation from docker instrustions.

**Comment by pbracs** [comment]
Hi,
I'm having the same problem.

Grafana Version : 6.1.6
Polystat plugin version : v1.1.0

**Comment by simon71** [comment]
I've just installed the plugin in out new k8s hosted grafana v6.4.5 and the plugin doesn't work. When selected the option fail to load, you just get a blank area.

**Comment by MatthiasDamm** [comment]
same here as @simon71

**Comment by orena1** [comment]
New version does not work for me also

**Comment by lmondoux** [comment]
Getting this error now as well after reinstalling grafana and this plugin.

**Comment by iamshreeram** [comment]
Plugin doesn't work for me as well. Any work around for this issue?

**Comment by zenmetsu** [comment]
Same issue here.

**Comment by briangann** [comment]
it has only been tested again v6.5.3 and higher, will try with older versions and see where it breaks, sorry for the delay responding.

**Comment by SailM23** [comment]
I have the same issue. @briangann, can you see if the steps to add the plugin grafana-polystat-panel in docker-compose.yaml are:
 grafana:
 container_name: xxx-grafana
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
      **- grafana-polystat:/var/lib/grafana/grafana-polystat-panel**
      - ./grafana-provisioning/:/etc/grafana/provisioning
    profiles:
      - grafana
    depends_on:
      - influx
    environment:
      <<: *influx-env
      <<: *grafana-env
      **GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-polystat-panel**
    ports:
      - "3000:3000"
    networks:
      - host-bridge-net
**volumes:
grafana-polystat:**

manual install of the plugin works in the grafana UI

s" usageStatsProvidersLen=2
telemetry-reference-tools-grafana                                  | logger=provisioning.datasources t=2022-06-24T22:33:43.93535816Z level=error msg="can't read datasource provisioning files from directory" path=/etc/grafana/provisioning/datasources error="open /etc/grafana/provisioning/datasources: no such file or directory"
telemetry-reference-tools-grafana                                  | logger=provisioning.plugins t=2022-06-24T22:33:43.935438262Z level=error msg="Failed to read plugin provisioning files from directory" path=/etc/grafana/provisioning/plugins error="open /etc/grafana/provisioning/plugins: no such file or directory"
telemetry-reference-tools-grafana                                  | logger=provisioning.notifiers t=2022-06-24T22:33:43.935482814Z level=error msg="Can't read alert notification provisioning files from directory" path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"
telemetry-reference-tools-grafana                                  | logger=ngalert t=2022-06-24T22:33:43.93702545Z level=info msg="warming cache for startup"
telemetry-reference-tools-grafana                                  | logger=http.server t=2022-06-24T22:33:43.949331091Z level=info msg="HTTP Server Listen" address=[::]:3000 protocol=http subUrl= socket=
telemetry

**Comment by jasonraymond** [comment]
This issue just popped up for me after upgrade from 10.1 to 10.5... Anyone else?

**Comment by chk212** [comment]
I have the same problem
