### ISSUE TITLE
Adding URL to clickthrough causes to loosing cells color

### ISSUE THREAD

**Issue by awer1967** [grafana/grafana-polystat-panel#117]
Hi !

 When I add a  link (no matter where) to polystat's clickthrough and try to refresh all the cells, those with the link turn into dark state (they completely loose their color). Check it, please, out. We have the last Grafana update installed.

Thanks in advance
Andrii.

**Comment by pbracs** [comment]
Hi,
We are having the same problem - color changes to dark and no link is presented.
