### ISSUE TITLE
Gradient colors results in black render with thresholds

### ISSUE THREAD

**Issue by mattgagliardi** [grafana/grafana-polystat-panel#126]
Setting up multiple (3+) thresholds with distinct color values, some of my entities (seems like those other than the highest/lowest threshold values) disappear...they render black.  Not sure why but turning off the gradient colors option seems to resolve the matter.

BTW...I absolutely love this plugin, it just looks so good.

![DELETE_Gradient-Off](https://user-images.githubusercontent.com/15810079/80099508-2c861600-8534-11ea-8323-16b2cfd46d47.JPG)
![DELETE_Gradient-On](https://user-images.githubusercontent.com/15810079/80099517-30199d00-8534-11ea-9f77-2cd137b7ef2f.JPG)

**Comment by mattgagliardi** [comment]
FWIW...it appears this may be related to [108](https://github.com/grafana/grafana-polystat-panel/issues/108) as taking the steps there also works.  Expanding a bit further...the "critical" level seems to work in a two-level scheme, but in the same two-level scheme if I select the "warning" level I get the black render issue.  Weird! :)

**Comment by briangann** [comment]
is this on safari by any chance?

**Comment by briangann** [comment]
fixed in v1.2.2
