### ISSUE TITLE
Allow tooltip to show up upon hover in edit mode

### ISSUE THREAD

**Issue by jericvizmanos** [grafana/grafana-polystat-panel#130]
**What would you like to be added:**
Allow tooltip to show up upon hover in edit mode

**Why is this needed:**
Once you enter edit mode, it's no longer easy to know the title or any info of the polystat cards. No information is showing up upon hovering over them.

Outside Edit Mode:
<img width="858" alt="Screen Shot 2020-06-16 at 9 55 44 AM" src="https://user-images.githubusercontent.com/58444570/84921787-c9b78380-b079-11ea-8053-8b3596cf7d1f.png">

Inside Edit Mode:
<img width="721" alt="Screen Shot 2020-06-16 at 9 53 59 AM" src="https://user-images.githubusercontent.com/58444570/84921807-cfad6480-b079-11ea-93ce-98609c8c422d.png">

**Comment by briangann** [comment]
this appears to be a side-effect of v7 only, investigating.

for v6 the tooltip still displays in edit mode.

**Comment by briangann** [comment]
looks like the z-index in the stylesheet will fix this, v7 has a zindex higher than the tooltip which causes this to not be displayed (it is actually there just invisible due to layering)
