### ISSUE TITLE
Tooltip width is to small and can't be changed

### ISSUE THREAD

**Issue by FireEmerald** [grafana/grafana-polystat-panel#133]
Current situation:
![polystat-width](https://user-images.githubusercontent.com/1107939/87937681-729c3880-ca95-11ea-9d71-fff077dd8e07.png)

Expected:
![polystat-tooltip](https://user-images.githubusercontent.com/1107939/87938014-2a314a80-ca96-11ea-9309-fb2ef9f62945.png)

The plugin needs some maintenance here and there...

---
**Edit:** Resizing the tooltip was already mentioned 2019 by Brian Gann in the grafana blog: https://grafana.com/blog/2019/04/16/grafana-plugin-tutorial-polystat-panel-part-2/#what-s-next

**Comment by briangann** [comment]
will be fixed in next release, this was a regression :(

**Comment by briangann** [comment]
fixed in release 1.2.1
