### ISSUE TITLE
Crash when adding a custom threshold

### ISSUE THREAD

**Issue by mccollam** [grafana/grafana-polystat-panel#135]
Using Grafana v7.1.0 (8101355285), Polystat 1.2.0

When creating a threshold in the polystat plugin, if the threshold color is changed to "custom" the plugin immediately crashes:

```
An unexpected error happened
TypeError: Cannot read property 'substring' of undefined
    in t
    in t
    in div
    in div
    in div
    in div
    in div
    in t
    in t
    in t
    in div
    in Wa
    in div
    in on
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l
```

Steps to reproduce:
1. Create a new dashboard and add a panel
2. Set the visualization to polystat and the datasource to the "--Grafana--" datasource
3. Add a threshold
4. Set the threshold color to "custom"
5. Observe crash

**Comment by briangann** [comment]
fixed in release 1.2.1
