### ISSUE TITLE
Polygon size cannot be changed in Grafana v7.1 and Polystat v1.2.0

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana-polystat-panel#136]
The polygons are auto-sized even with Auto disabled in the Sizing section.

The Polygon size in the two screenshots look slightly different due to the capture area and web scaling, but the pixel size of the Polygons are the same.

## Fixed size

![screenshot 2020-07-29 1340](https://user-images.githubusercontent.com/3270755/88834035-39547e80-d1a1-11ea-872f-56869ac6945c.png)

## Auto sizing

![screenshot 2020-07-29 1341](https://user-images.githubusercontent.com/3270755/88834042-3bb6d880-d1a1-11ea-9ef5-80c260439d2c.png)

**Comment by briangann** [comment]
this is a regression, will be fixed in v1.2.1

**Comment by srclosson** [comment]
https://github.com/grafana/grafana-polystat-panel/pull/141

**Comment by srclosson** [comment]
Potential fix for this issue.

**Comment by briangann** [comment]
fixed in release 1.2.1
