### ISSUE TITLE
No value displayed

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana-polystat-panel#14]
For some reason one cell shows no values here:

![image](https://user-images.githubusercontent.com/10999/45543258-68171500-b814-11e8-8d9a-74f2228e4ee1.png)

Will try add a test dashboard with this issue and others here (later, when I am done testing) 
https://github.com/grafana/grafana/tree/master/devenv/dev-dashboards

**Comment by momorientes** [comment]
Hi,

I'm not 100% sure if this is the same issue, but I still seem to encounter this bug on 1.0.15:

With disabled font auto scaling:
![image](https://user-images.githubusercontent.com/510293/53634417-70c0a380-3c1a-11e9-87de-8cefcaef53d1.png)

Once I enable font auto scaling all polygons are blank:
![image](https://user-images.githubusercontent.com/510293/53634470-8afa8180-3c1a-11e9-88a9-b93680fb5bdd.png)
