### ISSUE TITLE
Unable to install the 1.2.1 release via the grafana-cli

### ISSUE THREAD

**Issue by wiardvanrij** [grafana/grafana-polystat-panel#151]
I'm getting the following error:

```
/var/lib/grafana/plugins $ grafana-cli plugins install grafana-polystat-panel
installing grafana-polystat-panel @ 1.2.1
from: https://grafana.com/api/plugins/grafana-polystat-panel/versions/1.2.1/download
into: /var/lib/grafana/plugins

Error: ✗ failed to download plugin archive: Failed to send request: Get "https://storage.googleapis.com/integration-artifacts/grafana-polystat-panel/release/1.2.1/any/grafana-polystat-panel-1.2.1.any.zip": Forbidden
```

If I force version 1.2.0 it still works:

```
/var/lib/grafana/plugins $ grafana-cli plugins install grafana-polystat-panel 1.2.0 -d
getting plugin metadata from: https://grafana.com/api/plugins pluginId: grafana-polystat-panel
installing grafana-polystat-panel @ 1.2.0
from: https://grafana.com/api/plugins/grafana-polystat-panel/versions/1.2.0/download
into: /var/lib/grafana/plugins

Extracting archive /tmp/518969157.zip to /var/lib/grafana/plugins...
✔ Installed grafana-polystat-panel successfully

Restart grafana after installing plugins . <service grafana-server restart>
```

I'm not really sure what causes this.

**Comment by briangann** [comment]
haven't reproduced this yet, it is downloading in a docker install:

```
grafana_1  | installing grafana-polystat-panel @ 1.2.1
grafana_1  | from: https://grafana.com/api/plugins/grafana-polystat-panel/versions/1.2.1/download
grafana_1  | into: /var/lib/grafana/plugins
grafana_1  |
grafana_1  | ✔ Installed grafana-polystat-panel successfully
grafana_1  |
grafana_1  | Restart grafana after installing plugins . <service grafana-server restart>
grafana_1  |
```

Which OS and version of Grafana are you using?

**Comment by wiardvanrij** [comment]
```
/usr/share/grafana **$ grafana-cli -version**
Grafana CLI version 7.1.1

/usr/share/grafana **$ grafana-cli plugins install grafana-polystat-panel -d**
getting plugin metadata from: https://grafana.com/api/plugins pluginId: grafana-polystat-panel
Error: ✗ could not find the version you're looking for

/usr/share/grafana **$ grafana-cli plugins install grafana-polystat-panel 1.2.1 -d**
getting plugin metadata from: https://grafana.com/api/plugins pluginId: grafana-polystat-panel
installing grafana-polystat-panel @ 1.2.1
from: https://grafana.com/api/plugins/grafana-polystat-panel/versions/1.2.1/download
into: /var/lib/grafana/plugins

Error: ✗ failed to download plugin archive: Failed to send request: Get "https://storage.googleapis.com/integration-artifacts/grafana-polystat-panel/release/1.2.1/any/grafana-polystat-panel-1.2.1.any.zip": Forbidden
```

I'm running on k8s, grafana/grafana:7.1.1

**Comment by briangann** [comment]
thanks! i'll test this out

**Comment by briangann** [comment]
> /usr/share/grafana $ grafana-cli plugins install grafana-polystat-panel -d

can you omit the `-d` ?

**Comment by briangann** [comment]
this is what i'm getting:

```BASH
bash-5.0$ grafana-cli --version
Grafana CLI version 7.1.1
bash-5.0$ grafana-cli plugins install grafana-polystat-panel
installing grafana-polystat-panel @ 1.2.1
from: https://grafana.com/api/plugins/grafana-polystat-panel/versions/1.2.1/download
into: /var/lib/grafana/plugins

✔ Installed grafana-polystat-panel successfully

Restart grafana after installing plugins . <service grafana-server restart>
```

**Comment by briangann** [comment]
curious if there is a firewall or something in the way, can you curl/download the zip file directly? `https://storage.googleapis.com/integration-artifacts/grafana-polystat-panel/release/1.2.1/any/grafana-polystat-panel-1.2.1.any.zip`

**Comment by wiardvanrij** [comment]
> curious if there is a firewall or something in the way, can you curl/download the zip file directly? `https://storage.googleapis.com/integration-artifacts/grafana-polystat-panel/release/1.2.1/any/grafana-polystat-panel-1.2.1.any.zip`

Yes, that is possible. 
There is a proxy in place, but like I've shown before is that version 1.2.0 works without issues. 

As per request without debug:

```
/usr/share/grafana $  grafana-cli plugins install grafana-polystat-panel
installing grafana-polystat-panel @ 1.2.1
from: https://grafana.com/api/plugins/grafana-polystat-panel/versions/1.2.1/download
into: /var/lib/grafana/plugins

Error: ✗ failed to download plugin archive: Failed to send request: Get "https://storage.googleapis.com/integration-artifacts/grafana-polystat-panel/release/1.2.1/any/grafana-polystat-panel-1.2.1.any.zip": Forbidden
```

**Comment by briangann** [comment]
the download location changed - it was pulling from github.com and is now in GCS storage, usually s3/gcs are not blocked anywhere, but it may be for your network.

**Comment by jaymzh** [comment]
I have a related problem. It says it installed, but the old version is still reported:
```
# grafana-cli plugins install grafana-polystat-panel 1.2.1
installing grafana-polystat-panel @ 1.2.1
from url: https://grafana.com/api/plugins/grafana-polystat-panel/versions/1.2.1/download
into: /var/lib/grafana/plugins

✔ Installed grafana-polystat-panel successfully 

Restart grafana after installing plugins . <service grafana-server restart>

# grafana-cli plugins ls | grep grafana-polystat-panel
grafana-polystat-panel @ 1.1.0 
```

**Comment by briangann** [comment]
> I have a related problem. It says it installed, but the old version is still reported:

was grafana restarted before re-running the cli? it would report the currently running version if not.

**Comment by wiardvanrij** [comment]
> the download location changed - it was pulling from github.com and is now in GCS storage, usually s3/gcs are not blocked anywhere, but it may be for your network.

I would agree, but a simple wget actually downloads the version. It's just a bummer that Grafana CLI does not output more debug information.

**Comment by jaymzh** [comment]
> was grafana restarted before re-running the cli? it would report the currently running version if not.

Yes. IN fact that's how I noticed it, my configuration management system kept restarting grafana-server ;)

**Comment by briangann** [comment]
One more question: which version of grafana is being used? i'll try to replicate it with the same version, there could be a bug in the cli.

As a workaround, you can download it directly from here https://storage.googleapis.com/integration-artifacts/grafana-polystat-panel/release/1.2.1/any/grafana-polystat-panel-1.2.1.any.zip

in docker:

GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-polystat-panel/release/1.2.1/any/grafana-polystat-panel-1.2.1.any.zip;grafana-polystat-panel

**Comment by muryoutaisuu** [comment]
I'm not having the forbidden, but a different error:

```bash
bash-5.0$ grafana-cli plugins install grafana-polystat-panel 1.2.1 -d
getting plugin metadata from: https://grafana.com/api/plugins pluginId: grafana-polystat-panel
installing grafana-polystat-panel @ 1.2.1
from: https://grafana.com/api/plugins/grafana-polystat-panel/versions/1.2.1/download
into: /var/lib/grafana/plugins

Error: ✗ failed to download plugin archive: Failed to send request: Get "https://storage.googleapis.com/integration-artifacts/grafana-polystat-panel/release/1.2.1/any/grafana-polystat-panel-1.2.1.any.zip": x509: certificate signed by unknown authority
```

using grafana/grafana:7.1.3

Download works fine when using older version
`GF_INSTALL_PLUGINS=grafana-polystat-panel 1.2.0`

Maybe this helps?

**Comment by briangann** [comment]
haven't had more reports of this issue, re-open if you're still having problems installing via cli
