### ISSUE TITLE
Manual installation failed

### ISSUE THREAD

**Issue by franko108** [grafana/grafana-polystat-panel#153]
Hello, 

I'm trying to install the plugin within Gitlab Grafana (no _**grafana-cli**_ available).  
The package is unpacked in _/opt/gitlab/embedded/service/grafana/public/app/plugins/panel/grafana-polystat-panel/_    
Running commands:
```
$ yarn install
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.13s.
$ yarn build
yarn run v1.22.4
error Couldn't find a package.json file in "/opt/gitlab/embedded/service/grafana/public/app/plugins/panel/grafana-polystat-panel"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````
Is there anything more that I shall do here?  
Thanks, best,  
Franko

**Comment by cloudlady911** [comment]
I was able to use the cli with this command: /opt/gitlab/embedded/bin/grafana-cli --pluginsDir "/opt/gitlab/embedded/service/grafana/public/app/plugins" plugins install grafana-polystat-panel

However, the plugin does not work.
I get this error:
```
Error Loading Plugin
Check the server startup logs for more information.
If this plugin was loaded from git, make sure it was compiled.
```
Gitlab 13.3.7
Grafana 7.0.3
Not finding any help on this so far.

**Comment by danielserrao** [comment]
I have exactly the same issue. Did anyone found a solution for this?

**Comment by briangann** [comment]
for "external" plugins you normally extract them into /var/lib/grafana/plugins, and not into the main grafana installation (they will not get scanned/loaded during startup)

i will have to try this in gitlab, only idea now is to download and extract the zip file from our download page into the equivalent of "var/lib/grafana/plugins". the grafana.ini file specifies where additional plugins are installed.

**Comment by Taucher2003** [comment]
I'm facing the same issue. I was able to install the plugin with `/opt/gitlab/embedded/bin/grafana-cli plugins install grafana-polystat-panel` which was successful. But inside of grafana it still says, the plugin is not installed.


I was able to find this error in `gitlab-ctl tail`.
```
Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/var/opt/gitlab/grafana/provisioning/plugins error="open /var/opt/gitlab/grafana/provisioning/plugins: no such file or directory
```

**Comment by Taucher2003** [comment]
After some experiments, I found a working solution. In my case I installed the plugin like mentioned by @cloudlady911 
> I was able to use the cli with this command: /opt/gitlab/embedded/bin/grafana-cli --pluginsDir "/opt/gitlab/embedded/service/grafana/public/app/plugins" plugins install grafana-polystat-panel

After that was successful, I added a symlink from `/var/lib/grafana/plugins/` to `/var/opt/gitlab/grafana/data/plugins/`.
(`ln -s /var/lib/grafana/plugins/ /var/opt/gitlab/grafana/data/plugins/`) and restarted grafana. This seems to be a working solution.

I don't know if that file are going to be overwritten when Gitlab updates the embedded Grafana or if this files will stay unchanged.

**Comment by briangann** [comment]
i'll add this to the docs, will be useful for others!
