### ISSUE TITLE
Polystat circle or square shape with ClickThrough URL, drilldown does not work and fill color always black

### ISSUE THREAD

**Issue by AnushaBoggarapu** [grafana/grafana-polystat-panel#154]
Select shape as square\circle
The color coding is intact.
Give some click through URL, the squares and circles become black color.

This does not happen with Hexagons again.

Polystat- latest version (1.2.2)
Grafana 7

**Comment by AnushaBoggarapu** [comment]
In this case the drilldown also never works, when shape is square or circle.

**Comment by matletix** [comment]
Related to #117

**Comment by briangann** [comment]
is this on safari by any chance?

**Comment by matletix** [comment]
> is this on safari by any chance?

@briangann Yes, I replicated the issue with safari 13.1.1 and grafana-polystat-panel v1.2.2 on MacOS Catalina 10.15.5
