### ISSUE TITLE
Unable to Disable Hover Over Tooltips

### ISSUE THREAD

**Issue by K3User** [grafana/grafana-polystat-panel#155]
Using the options in the Grafana Plugin Panel for Polystat, we are unable to disable the tooltips from showing up, regardless if enabled or not. Are we missing something to be able to not have these show up as they are very annoying and not needed in our case? Our hexagons are linked to launch other grafana pages.

![grafana_plugin_panel_tooltip_selection](https://user-images.githubusercontent.com/71782627/94043632-3211b180-fd9b-11ea-8a41-c092f2caeb1f.PNG)

![grafana_plugin_panel_tooltip_hover](https://user-images.githubusercontent.com/71782627/94043690-3e960a00-fd9b-11ea-83f7-1c9cfe244505.PNG)

**Comment by briangann** [comment]
Added in v1.2.3
