### ISSUE TITLE
Creating a composite of an override copy the clickthrough url of the composite to the override

### ISSUE THREAD

**Issue by matletix** [grafana/grafana-polystat-panel#160]
Steps to reproduce:

1. Create a query with an alias
2. Create an override that reference the previous alias
3. Create a composite, add the previous alias as a metric of the composite, and toggle the "Hide members" option so that both the composite and the metric polygons are dispalyed.
4. Add an url in the clickthrough field of the composite and save the panel
5. Click on the metric polygon. It redirects you to the url entered in the composite clickthrough url field.

If an URL is entered in the global default clickthrough field or in the override clickthrough field, it is ignored in favor of the url of the composite.

Is this expected behaviour ?

Grafana version : 7.2.1
grafana-polystat-panel version : 1.2.2

**Comment by briangann** [comment]
definitely a bug, it should be honoring the "standalone" polygon's url specified in the override, and not the composite.
