### ISSUE TITLE
Tooltip move out of range on hover

### ISSUE THREAD

**Issue by matletix** [grafana/grafana-polystat-panel#163]
When hovering over a polygon (metric, composite or override), it initially shows the tooltip where the cursor is :

![Screenshot_20201124_103210](https://user-images.githubusercontent.com/19894690/100076736-d36fbf00-2e41-11eb-9835-0eed4512a3a5.png)

But if the cursor is letf without moving over the polygon, the tooltip moves out of range after 2 or 3 seconds :

![Screenshot_20201124_103247](https://user-images.githubusercontent.com/19894690/100076882-fbf7b900-2e41-11eb-8f9d-ec89a6424a43.png)

I tried with Firefox 82 and Chrome 86, both displaying the issue.

Grafana version : 7.2.1
grafana-polystat-panel version : 1.2.2

**Comment by matletix** [comment]
I noticed this is actually due to the auto-refresh feature of grafana that was set to 5 seconds. When the dashboard auto-refreshes, the tooltip moves out of range.

**Comment by briangann** [comment]
definitely a bug, the tooltip relies on mouse events to position it, on a refresh the mouse doesn't move. we'll need to add state for last position.
