### ISSUE TITLE
Bug when using the "repeat" feature with a variable in a composite name

### ISSUE THREAD

**Issue by matletix** [grafana/grafana-polystat-panel#168]
This issue occurs when using the "repeat" feature to repeat a panel several times on a dashboard, with multiple values for the repeated variable. If the variable is used in a composite name, then several composites per panel are created.

**Example** : I create a panel with ONE composite, and I set the composite name to `$hostname`. I repeat this panel along the `$hostname` variable. I select two values for this variable in the dashboard : `example-hostname` and `example-hostname-2`.

**Expected**: one panel with one composite `example-hostname`, another panel with another composite `example-hostname-2`.

**Actual behaviour**: one panel with two composites `example-hostname` and `example-hostname-2`, both displaying the actual state of `example-hostname`. Another panel with the same two composites, but displaying the actual state of `example-hostname-2`.
Result below (the title of the panel is set to `$hostname`) :

![image](https://user-images.githubusercontent.com/19894690/102374844-1a288300-3fc2-11eb-91e4-9c4059154842.png)

**Comment by matletix** [comment]
May be linked to #161

**Comment by a-vogel-tappert** [comment]
Issue still exists. Any plans when to fix it ?

**Comment by amaspastor** [comment]
Any news on a fix for this bug ?

**Comment by oshirohugo** [comment]
@matletix are you still having this issue with the last plugin version?
If yes, could you give us more details. What Grafana version and plugin version you're using and how are you are generating this panel. If possible please share your dashboard.

I've tried to reproduce this issue. with data frames generated by `testData` datasource, and crating one composite with $hostname as name. And everything worked as expected.

Here is the exported dashboard:
https://gist.github.com/oshirohugo/fa6c75cf0bcf0e2aac4bc5dcf12b838a

I've used:
Grafana v10.1.1
Polystat 2.1.2

**Comment by matletix** [comment]
@oshirohugo I don't have access to the project with the bug anymore and I see I didn't mention the versions I used when I created the issue, sorry for that. If you can't reproduce I guess we can close this and reopen if/when someone has the data for reproducing.

**Comment by oshirohugo** [comment]
Closing this issue as it could be not reproduced.
