### ISSUE TITLE
Misc questions & bugs

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana-polystat-panel#17]
**Shape** 
Switching between The Hexagon Pointed Top and Hexagon Flat Top makes no difference. The other shapes don't make a lot of sense to me. I would prefer if we removed this option and only supported one hexagon shape (and maybe the circle shape). 

**Stat** 
Count, Current, Delta, etc not working. 

**Animation: **
What does this option do? 

**Layout:**
![image](https://user-images.githubusercontent.com/10999/45548564-06ab7200-b825-11e8-8e48-4d4ef051641e.png)

After testing these options I have been unable to remove the 1 (or any value), it always returns to 1 after clearing columns or rows. 

What does AutoSize for columns and rows? It has no effect when I try it (tested it with differnet rows and column options and configurations). 

**Tooltip**
* Do we need a font option? 
* Should use same font as Grafana (Roboto) 
* Can we use the styles from the graph tooltip or copy the look (background)

**Font Size** 
* Can we hide the font size option when auto font size is enabled? As the auto option is after the font size option, I kept trying to change it without any effect.

**Comment by csalvatierra-technisys** [comment]
> After testing these options I have been unable to remove the 1 (or any value), it always returns to 1 after clearing columns or rows.

You can edit the json model. Go to your dashboard's settings, pick JSON Model, then edit the "rows" property. You must omit its value. like this:

![imagen](https://user-images.githubusercontent.com/26311413/68812782-e2723d80-0641-11ea-8e81-0ba0024776cd.png)
