### ISSUE TITLE
Thresholds don't work for composites without overrides

### ISSUE THREAD

**Issue by mjiderhamn** [grafana/grafana-polystat-panel#173]
For composites, [`getWorstSeries()`](https://github.com/grafana/grafana-polystat-panel/blob/master/src/threshold_processor.ts#L56) makes use of [`getThresholdLevelForValue()`](https://github.com/grafana/grafana-polystat-panel/blob/master/src/threshold_processor.ts#L82) to determine threshold value given value and `thresholds`. However, [`MetricOverridesManager.applyOverrides`](https://github.com/grafana/grafana-polystat-panel/blob/master/src/metric_overrides_manager.ts#L122) sets the `.thresholds` property [only in case overrides are used](https://github.com/grafana/grafana-polystat-panel/blob/master/src/metric_overrides_manager.ts#L149). The `.thresholdLevel` property however seems to be set in [both](https://github.com/grafana/grafana-polystat-panel/blob/master/src/metric_overrides_manager.ts#L140) [cases](https://github.com/grafana/grafana-polystat-panel/blob/master/src/metric_overrides_manager.ts#L173).

**Comment by matletix** [comment]
Thank you for pinpointing that ! Seems related to #158

**Comment by briangann** [comment]
Fixed, will be in v1.2.3
