### ISSUE TITLE
Value mapping "0"

### ISSUE THREAD

**Issue by eglyn** [grafana/grafana-polystat-panel#182]
Hi :)

I just want to map value "0" to "Offline" and value "1" to "Online", but it works only to "1" value.
"0" value stay to 0, I don't know why :/

Any idea ? 

![image](https://user-images.githubusercontent.com/24936778/111961105-e4c79000-8af0-11eb-82e4-db587323c331.png)

![image](https://user-images.githubusercontent.com/24936778/111961126-ed1fcb00-8af0-11eb-8dda-47fd6a10af9d.png)

**Comment by matletix** [comment]
Hi,

Which version of the grafana-polystat plugin are you using ?
Is this happening with a basic metric, an override or a composite ?

**Comment by eglyn** [comment]
I have the latest version: 1.2.3
It is a basic metric, just a "host alive" result: 0 = offline, 1 = online.

**Comment by eglyn** [comment]
Threshold with color is OK, 0 = orange and 1 green, but value replacement works only with number 1, not 0

**Comment by eglyn** [comment]
Ok, i just find a workarround... I use range 0 --> 0 and it works :D

**Comment by matletix** [comment]
Yep, just tried it and this happens in v1.2.0, v1.2.1, v1.2.2, v1.2.3.
It's a bug, will need to be fixed, you can use the range workaround for now.
