### ISSUE TITLE
Override changes are not holding after applying

### ISSUE THREAD

**Issue by satyatechy** [grafana/grafana-polystat-panel#183]
When we use Polystat and apply override for a particular series name then changes are visible in the edit mode, but after applying and coming back to dashboard view the changes are not visible and when we go back to edit mode the changes will be there. Only if we save and refresh the dashboard then only changes will be visible in the dashboard view permanently
<img width="960" alt="Polystat in Editmode" src="https://user-images.githubusercontent.com/65600879/112419387-5b62c880-8d51-11eb-8520-f2da9c96bda0.png">
<img width="959" alt="Polystat in dashboard view where changes are missing" src="https://user-images.githubusercontent.com/65600879/112419413-63bb0380-8d51-11eb-8c53-44df1844da88.PNG">

. 

Steps to reproduce:

1. Create a panel query using polystat.
2. Apply override for a particular series, the changes will be visible.
3. Apply and come back to dashboard view the changes will not be there.
4. Now save and refresh the dashboard the changes will be back again.

Expected: The changes that we do in edit mode should be visible even after applying and in dashboard view without saving and refresh.

Version:

Grafana: 7.2 and above
Polystat: 1.2.1
Datasource: Any

**Comment by briangann** [comment]
it's a bug that's been there for a long time, will look into fixing it. same issue happens with composites.

**Comment by AKhares** [comment]
We are also seeing the same issue. Is there any work happening to fix this issue. Please suggest if there are any workarounds.

**Comment by briangann** [comment]
should be fixed in latest release, reopen if you see this happening again.
