### ISSUE TITLE
"No data" mapping to error

### ISSUE THREAD

**Issue by a-mazed** [grafana/grafana-polystat-panel#185]
Hello!
Is there any option to display any information about "No data" state or treat this state as 0 or error? I need this to handle it as errors.
For example, the Stat plugin displays "No data" and it's possible to choose red color for background for these cases.

Stat plugin
![image](https://user-images.githubusercontent.com/25726917/113135678-0fb98e80-922b-11eb-9769-f06ae545a4f1.png)

Polystat plugin
![image](https://user-images.githubusercontent.com/25726917/113135728-219b3180-922b-11eb-80dc-4fcc7ca3f655.png)

**Comment by briangann** [comment]
adding a value mapping of "null" to text can be done, or numerical so it will use the threshold value. current there is no text based threshold option.

**Comment by alesabino172** [comment]
In Standard options, put 0 in the No Value property.

**Comment by majerus1223** [comment]
@alesabino172 do you have a screenshot of this by chance? I cannot find a "no value property". Thanks!
