### ISSUE TITLE
Layout and sizing with fixed polygon size can lead to hidden polygons

### ISSUE THREAD

**Issue by daesign-dev** [grafana/grafana-polystat-panel#187]
Trying to display a simple state of 32 services, I first use full autosizing but the place used was so strangely optimized.
Just one row here:
![image](https://user-images.githubusercontent.com/15905901/113906361-7531f000-97d4-11eb-8f54-499203d81cfd.png)
and only starts to use a second row when upsizing the height here:
![image](https://user-images.githubusercontent.com/15905901/113905995-0e143b80-97d4-11eb-97b9-e010fc9466b6.png)

I then try to fix the polygon size to make it more readable but then some polygons are hidden even if it seams to be a lot of room in height:
![image](https://user-images.githubusercontent.com/15905901/113906727-d78af080-97d4-11eb-9451-0a09c47bc86c.png)

Here, I can see them all:
![image](https://user-images.githubusercontent.com/15905901/113906969-1caf2280-97d5-11eb-94bd-9a57cbd93f98.png)

but they seems to disappear step by step on the right side when reducing the pane height:
![image](https://user-images.githubusercontent.com/15905901/113907132-49633a00-97d5-11eb-95e2-26beb0288a5d.png)

![image](https://user-images.githubusercontent.com/15905901/113907188-5c760a00-97d5-11eb-98bb-d43f80a01b80.png)

even if they should be displayed, all of them, on 2 rows.

**Comment by briangann** [comment]
definitely a bug in the auto-layout, it should not be truncating like that.

you'll have better results specifying the number of rows and columns to get the panel layout, along with the polygon size option.

the auto-layout prefers columns over rows, and tries to pack as many items possible into a single row, i think that should be made configurable so the preference can be rows over columns also.

**Comment by briangann** [comment]
the truncating bug is due to the auto-layout calculating the columns and rows and ignoring the manually set "polygon size = 50"
