### ISSUE TITLE
Missing value in tooltip after upgrade to 8.0.0-beta3

### ISSUE THREAD

**Issue by mguggi** [grafana/grafana-polystat-panel#190]
After upgrading Grafana to 8.0.0-beta3 the values in the tooltip are missing. At the moment I've no idea if the issue is Grafana or the Polystat panel. 

<img width="144" alt="Screenshot 2021-06-04 at 10 02 27" src="https://user-images.githubusercontent.com/13131781/120768429-6f2e6600-c51c-11eb-907d-a97e7c68b804.png">

**Comment by xenofree** [comment]
Same here with grafana 8.0.0

**Comment by eglyn** [comment]
Same here with Grafana 8.0.0
No value into polygons :/
But threshold works.

**Comment by r4wr** [comment]
This issue is still present in Grafana 8.0.1.

**Comment by eglyn** [comment]
I confirm, same issue on 8..0.1 :'(

**Comment by r4wr** [comment]
Looks like the issue is still present in 8.0.2.

**Comment by briangann** [comment]
i'm looking into this bug

**Comment by briangann** [comment]
this is due to a change in the v8 data api, working on a fix to keep it backwards compatible.

**Comment by r4wr** [comment]
Looks like this fix completely broke my polystat panel. Is there any way to revert back to 1.2.3 when using provisioning? I can deal with missing values for now.

**Comment by r4wr** [comment]
> Looks like this fix completely broke my polystat panel. Is > there any way to revert back to 1.2.3 when using >provisioning? I can deal with missing values for now.

I was able to revert to 1.2.3 for now. 1.2.4 doesn't show any errors, just no longer shows the composite hexagons and is blank.

**Comment by eglyn** [comment]
> Looks like this fix completely broke my polystat panel. Is there any way to revert back to 1.2.3 when using provisioning? I can deal with missing values for now.

Thx for feedback, I will wait next update ^^; maybe this thread needs to be re-open ?

**Comment by mguggi** [comment]
<img width="204" alt="Screenshot 2021-06-25 at 14 40 38" src="https://user-images.githubusercontent.com/13131781/123426464-bcee3980-d5c3-11eb-8d5c-debf14175d59.png">

<br>

<img width="780" alt="Screenshot 2021-06-25 at 14 40 51" src="https://user-images.githubusercontent.com/13131781/123426526-d1323680-d5c3-11eb-8184-8f6d4b33656f.png">


I've no clue why one Polystat is shown and the other not? Maybe the total number of queries? In my case this are 43 queries. But when the Polystat is shown also the tooltip values are there.
