### ISSUE TITLE
Value 0 = no display

### ISSUE THREAD

**Issue by eglyn** [grafana/grafana-polystat-panel#196]
Hi, 
Since the last update, if a request return 0 as value, panel does not display, only black screen.

For example, I request a "host alive" wich return 0 for down and 1 for up.
If in my requests I have a 0, panel does not display.

With Stat panel : (red =0, green = 1)
![image](https://user-images.githubusercontent.com/24936778/123099868-df048200-d432-11eb-92fc-e731cd3f35a7.png)

With Polystat: (nothing)
![image](https://user-images.githubusercontent.com/24936778/123099961-f5aad900-d432-11eb-8437-23108a9fd73e.png)

And if I disable the request wich return 0, panel come back: 
![image](https://user-images.githubusercontent.com/24936778/123100065-0fe4b700-d433-11eb-99e0-44e4f12cdf34.png)

If I go in query inspector, and refresh data, in the data tab, there is a infinite loading...
![image](https://user-images.githubusercontent.com/24936778/123099754-c4caa400-d432-11eb-9fb7-4f351262a69f.png)

**Comment by briangann** [comment]
Fixed in #195, will publish this today

**Comment by eglyn** [comment]
Thx it works now :)
