### ISSUE TITLE
Clickthrough URL Cannot Locate Dashboard

### ISSUE THREAD

**Issue by gsperry2011** [grafana/grafana-polystat-panel#204]
Using Grafana v8.1.1 (90c87a52f7)

Recently I discovered that my click through URL's no longer are working from my Polystat panels.

This doesn't work (but used to): `dashboard/db/node-exporter-linux`
This does work, but has a unique ID in the URL which means this doesn't work across multiple environments:  `/d/rYdddlPWk/node-exporter-linux` 

When I attempt to use the click through I get:
![image](https://user-images.githubusercontent.com/21208713/128880302-6b9fe983-a8b5-4d78-8ba7-f32ffd260db7.png)

Is this expected to be broken now? Is there a way to create clickthrough URLs **without** the unique ID in the URL, so it works across multiple Grafana environments?

I found this: https://grafana.com/blog/2019/04/02/grafana-plugin-tutorial-polystat-panel-part-1/ which has this as an example URL:  `dashboard/db/cassandra?var-environment=$Cluster&var-instance=All` which looks very close to what used to work for me but no longer is.

**Comment by gsperry2011** [comment]
Update in case anyone is having a similar issue to me:

You can control the UIDs in your dashboards, you do not have to use the UID's generated by grafana. Simply go into the json file when you save and export your dashboard and you will see `uid` listed near the bottom of the file, you can put whatever you want in there (I assume it needs to be unique being a UID and all...)

That means you can know what the UID will be before hand so you can create URL links that will work across multiple environments, because you are controlling what the UID is!

That means `/d/rYdddlPWk/node-exporter-linux` becomes `/d/<whatever-UID-you-want-here>/<dashboard-name-here>`

**Comment by briangann** [comment]
the naming convention `dashboard/db/dashboard-name` was scheduled for deprecation, v8.1 likely removed it (will double check)

**Comment by Nik9044** [comment]
My variable name contains + sign which is removed when redirected to the linked dashboard, hence showing no data due to variable mismatch, any idea how to pass + sign.

**Comment by menvol3** [comment]
@Nik9044 Did you find the solution to how to pass + sign?
