### ISSUE TITLE
Sort Direction: Numerical (asc/desc) and Sort Field:Value not working

### ISSUE THREAD

**Issue by satyatechy** [grafana/grafana-polystat-panel#205]
**What happened:** Sort Direction: Numerical (asc/desc) and Sort Field:Value not working

**What you expected to happen:** Sort Direction: Sorting should work properly when we select Sort DIrection:  Numerical (asc/desc)

**How to reproduce it (as minimally and precisely as possible):** Build a query and select visualization type as Polystat. Now apply sorting order sort direction as: Numerical (asc/desc) and Sort Field: Value. 

<img width="960" alt="Sorting Issue" src="https://user-images.githubusercontent.com/65600879/132334952-1b3c933b-0449-4592-b1e9-fd598962b411.png">

**Anything else we need to know?:**
 It works properly when we select Sort direction: Alphabetical (asc/desc) and Sort field: Value but not as we would expect (ie numerical / value).

**Environment:** Any

Grafana version: 7.5.5
Data source type & version: Any
OS Grafana is installed on: Any
User OS & Browser: Any
Grafana plugins: Polystat 1.2.6
Others:

**Comment by briangann** [comment]
definitely a bug, looking into this now
