### ISSUE TITLE
All nodes showing same load value

### ISSUE THREAD

**Issue by gbeyer3** [grafana/grafana-polystat-panel#207]
Why are all of my polys showing the same value for node load?  If I look at the same query with a time series, a gauge or bar chart, each node shows its own load value.  Likewise in a plain old Prometheus query, each nodes shows its own load.  And that 1009.00 value bares no relationship to anything I can figure out.
![image](https://user-images.githubusercontent.com/79545628/134577396-c2c37b42-8fa2-4e2c-8cbf-84fda5aa2ddb.png)

**Comment by briangann** [comment]
does your query include a group by function? 

the query above shouldn't have that type of output, looks like a bug.

**Comment by briangann** [comment]
using a similar query i don't get that type of result, here's the query and output, do you have the full query to share with aliasing?

![image](https://user-images.githubusercontent.com/7364245/135560325-4be7a8f9-117c-474b-9527-65f66fbe93ea.png)

![image](https://user-images.githubusercontent.com/7364245/135560304-b1fbcaa9-1b9b-411c-8f8d-0f6f7309f88b.png)
