### ISSUE TITLE
Ability to rename overrides?

### ISSUE THREAD

**Issue by dwilliams782** [grafana/grafana-polystat-panel#210]
Hi,

I have set up a test dashboard with automated composites, as seen [here](https://github.com/grafana/grafana-polystat-panel/issues/45)

With this, we are going to end up with dozens and maybe even hundreds of overrides to configure different thresholds per metric. 

![image](https://user-images.githubusercontent.com/42545485/142241981-362d53a0-522d-4e5f-ba2b-44911543cf0e.png)

With this, it would be really useful to rename overrides to be more meaningful.

**Comment by briangann** [comment]
That should be fairly easy to implement, will add it for the next release.

**Comment by jeremyschulman** [comment]
As a workaround, I found that I could edit the JSON from the dashboard edit screen so that I can customize the names.

**Comment by jeremyschulman** [comment]
If it is also possible to name the COMPOSITE as part of the feature-request that would be much appreciated!
