### ISSUE TITLE
Migrate polystat panel to react

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana-polystat-panel#218]
**Why?**
We are moving towards [deprecating](https://community.grafana.com/t/were-deprecating-angular-based-plugins/62673) angular based plugins in Grafana. Even though it will take a while (possibly a year+) until we actually remove the support, we should start migrating plugins written by us to use react instead of angular. 

**Acceptance criteria**
- Angular is not used in the plugin anymore
- We have documented the learnings from migration 
- New version of [polystat panel plugin](https://grafana.com/grafana/plugins/grafana-polystat-panel/) is published targeting Grafana `8.3+`
- If some functionality was removed / not possible to replace it is documented in the [plugins changelog](https://grafana.com/grafana/plugins/grafana-polystat-panel/?tab=changelog)

**Comment by tolzhabayev** [comment]
@briangann FYI - in case you are using `getColorForTheme` in the new version of the plugin - it is removed in v9 and should not be used https://github.com/grafana/grafana/pull/49519

**Comment by tolzhabayev** [comment]
As discussed in daily - we need a patch for Grafana 9 to fix getColorForTheme

**Comment by briangann** [comment]
Fixed by #238 and other PR's
