### ISSUE TITLE
Unable to use URL Variables in ClickThrough

### ISSUE THREAD

**Issue by warmfusion** [grafana/grafana-polystat-panel#221]
Hi,

I'd like to have a ClickThrough link based on the fields of my prometheus response such that i can show a set of hex's that represent different 'services' and have a click that takes to a more detailed view for that particular service.

I've been trying to use a url like this; `/d/abcEFGHi/detail-view?${Datasource:queryparam}&var-owner=${__field.label.owner}&${__url_time_range}`

However the clickthrough url is always incomplete.

The `${Datasource:queryparam}` is properly set, while the var-owner and $__url_time_range values are not replaced as expected.

I've tried;

- ${__field.labels.owner}
- ${__field.label.owner}
- ${__field.label["owner"]}
- ${__series.name}
- $__series.name

Data being shown by polystat;
``` json
{
  "request": {
    "url": "api/datasources/proxy/2/api/v1/query",
    "method": "POST",
    "data": {
      "query": "slo:period_error_budget_remaining:ratio{owner=~\"Redacted Systems\"}",
      "time": 1651363199
    },
    "hideFromInspector": false
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "vector",
      "result": [
        {
          "metric": {
            "__name__": "slo:period_error_budget_remaining:ratio",
            "category": "availability",
            "owner": "Redacted Systems",
            "prometheus": "kube-prometheus-stack/kube-prometheus-stack-prometheus",
            "prometheus_replica": "prometheus-kube-prometheus-stack-prometheus-0",
            "region": "redacted-prod",
            "repo": "redacted/redacted-api-service",
            "sloth_id": "redacted-redacted-service-requests-availability",
            "sloth_service": "redacted-redacted-service",
            "sloth_slo": "requests-availability",
            "sloth_window": "30d"
          },
          "value": [
            1651363199,
            "0.9991794509250443"
          ]
        }
      ]
    }
  }
}
```
It never gets replaced properly.

Polystat Version : 1.2.8
Grafana Version : v8.2.3 (fb85ed6912)

**Comment by warmfusion** [comment]
# Workaround

Based on some fairly messy tricks, i've managed to make a workaround after reading the [clickthrough  transformer source](https://github.com/grafana/grafana-polystat-panel/blob/master/src/clickThroughTransformer.ts#L8-L16);

Using the undocumented regex title matching i've been able to pull values from the cell title and use it in the click through. its not very robust, and i can't get the title of the panel which means the `var-owner` isn't set here, but in general its _functional_

<img width="604" alt="Screenshot 2022-05-04 at 10 22 55" src="https://user-images.githubusercontent.com/2294568/166655370-b3a291d8-15e0-455a-81c8-45d03a908587.png">

**Comment by menvol3** [comment]
Hi @warmfusion 

I'm facing mostly the same issue, maybe can help to resolve it

I have a text in my metric legend that looked like below 

`some_email+some_text@domain.com SOME_TEXT`

To parse it I'm using the regex  expression below

`(^\S*)\s+(.*)` and all works except encoding  `+` from the first var to URL format which should be 

After parsing it looks like this `some_email some_text@domain.com SOME_TEXT`, where plus is replaced by whitespace

**Comment by briangann** [comment]
let's see about getting this fixed and documented well enough to offer examples of it in action.

the templated composites are tricky in the same manner, and the templated overrides are not documented.  There will be some showcase dashboards that demonstrate how to do more complex setups.

**Comment by glerma** [comment]
Has there been any progress with this?
