### ISSUE TITLE
Grafana 9.0.0: Polystat Panel Rendering Incorrectly

### ISSUE THREAD

**Issue by cassidy3** [grafana/grafana-polystat-panel#225]
Hi there! We're trying out 9.0.0 in our dev environment, and we're seeing an issue that might be related to the blank panels you're referring to in #223.

We're running the grafana/grafana-enterprise:9.0.0 Docker image with Polystat version 1.2.9. Polystat panels show up entirely blank, and once we edit the size or placement of the hexagons, they show up as all black like in the image below. We can highlight the text in them so it just appears to be a rendering issue. We've tested multiple browsers on multiple machines with the same issue, and have tried playing around with the panel settings but it appears to be fairly persistent. This certainly isn't priority as we don't use Polystat for anything crucial (plus it's in our dev environment), but I wanted to bring it to your attention anyways since it may be affecting others.

![image](https://user-images.githubusercontent.com/15707989/173875158-c537940c-027c-4543-b7c5-7ca9dce68480.png)

**Comment by tczerwonka** [comment]
I'm also seeing this using polystat v1.2.9 on grafana-9.0.0-1.x86_64 on rhel7.  I tried re-creating the same panel and found the polygons appear with name and value if I resize the panel slightly.  The following may be unrelated but on the duplicated panel I'm seeing the values displayed are full values (e.g. -0.33172827284) and not truncated with the specified number of decimals, "-0.33" and color doesn't change with threshholds.

**Comment by briangann** [comment]
the release for 1.2.9 was to address this (tested against beta3), will double check 9.0.0 to see if I can reproduce it.

**Comment by briangann** [comment]
reproduced it - something changed between 9.0.0-beta3 and the release, will have a fix shortly.
