### ISSUE TITLE
Polystat panel not working anymore after Grafana update to 9.0.1

### ISSUE THREAD

**Issue by svestenik** [grafana/grafana-polystat-panel#228]
Hi Team,

after I updated my Grafana OSS version to 9.0.1, all Polystat panels stopped working.
I am using InfluxDB 1.8 as data source and other panels still work, so data source connectivity is not a issue.

Anyone seen the same behavior and what can be done to fix this ?

**Comment by briangann** [comment]
You will need to update to v1.2.11 for v9.0+, 1.2.10 does work but it has issues with valuemaps/rangemaps. Previous versions would not render at all in v9.

**Comment by Dokiel** [comment]
hi team,
I have updated grafana to: 9.0.2 and I have version 1.2.11 of Polystat, but all the views I had with Polystat stopped working, any recommendation?

**Comment by Natreg** [comment]
Hello,

I'm having the same problem. We recently updated to Grafana version 9.0.3 and we are using Polystat 1.2.11 and all panels have stopped working.

Any suggestions?

**Comment by briangann** [comment]
looking into this, will have a fix shortly

**Comment by nicolastakashi** [comment]
I'm using the latest grafana version 9.0.4 with Poly Panel and everything is working as expected.

**Comment by battosai30** [comment]
Hi,
I don't know if it's linked but :
Fresh install of Grafana (v9.0.6) on Windows Server + polystat 1.2.11 => panel's configuration is not saved :s

**Comment by svestenik** [comment]
After upgrade to Grafana 9.0.6 my polystat panels stopped working again (First time happened with update to Grafana 9.0.1). 

I had to delete and create them again to get them to work.

**Comment by tekkamanendless** [comment]
Ah, so apparently you have to update the Polystat plugin from _within_ Grafana at the `/plugins` URL (under "Configuration").

**Comment by briangann** [comment]
I'll update the docs with the various methods of installing/updating.  With grafana cloud you update plugins via the portal, with the internal plugin config it is handled in /plugins, and there's the local method of grafana-cli, docker, and environment variables.

**Comment by manuel-held** [comment]
With Grafana 9.1.1 i get

`msg="Skipping loading plugin due to problem with signature" pluginID=grafana-polystat-panel status=unsigned`

this in the Logs.
