### ISSUE TITLE
[enhancement] Support `Search Options` feature of Grafana 8+

### ISSUE THREAD

**Issue by mvadu** [grafana/grafana-polystat-panel#232]
Grafana 8+ supports searching for all options for a panel. Current version of PolyStat doesn't support it and we get a message `This is an old visualization type that does not support searching all options.` 

![image](https://user-images.githubusercontent.com/8618235/181287379-11cd93bd-f9af-4cc0-95e0-cec9e7262165.png)

Is this something in the roadmap to support?

**Comment by briangann** [comment]
Yes, it will be part of the react migration for v2.0

**Comment by briangann** [comment]
fixed in release of v2 #233
