### ISSUE TITLE
Rename by Regex transformation not working when using Dashboard variables that are passed to "Name" in Polystat

### ISSUE THREAD

**Issue by marinnedea** [grafana/grafana-polystat-panel#240]
Grafana 8.5.5 enterprise
Polystat latest version

The issue happens when using Dashboard variables only!

When trying to manage the Name from the Polystat, and manipulate the naming from "percentage A1" to show as "A1" via transformation "Rename by regex", as soon the transformation is selected, the A1 disappears from the Name . This happens regardless if there's any regex string or not in the Match and/or Replace fields.

![image](https://user-images.githubusercontent.com/7581631/196653320-f967a3ab-62d8-488c-9d39-086854c395df.png)

Here’s the query and table view for your reference.
![image](https://user-images.githubusercontent.com/7581631/196653445-f7b6679a-a9f9-4bdf-876b-2e99c4e65d99.png)

**Comment by nidhisht** [comment]
Additionally, Column name "**percentage**" is automatically being prefixed in the label of polygon. Not sure if that is by design or a bug.

"**Rename by regex**" is not helping to remove "percentage" word from polygon (as discussed in the original thread of the post). Kindly advise.

**Comment by tolzhabayev** [comment]
@marinnedea 
with the new [2.0.2 update](https://github.com/grafana/grafana-polystat-panel/releases/tag/v2.0.2)

It can now be achieved by:
- using global regex 
![SCR-20221103-ely](https://user-images.githubusercontent.com/580672/199687829-2aa07bfc-953d-43f4-bb60-fab9c963a419.png)

**Comment by marinnedea** [comment]
Thank you! All seems ok now.

**Comment by nidhisht** [comment]
Grafana 9.2.4
Polystat plugin 2.0.3

Thank you for the suggestion. "percentage" prefix issue is resolved with global regex. However that introduced another issue - Panel is showing only one polygon after upgrading polystat panel to 2.0.3 version. 
![image](https://user-images.githubusercontent.com/42999787/203524115-76bbeed2-7728-4207-bff2-ef551b123ba7.png)

Here's the query and table view for your reference.
![image](https://user-images.githubusercontent.com/42999787/203524247-30319cce-57bf-497a-aeef-f43c735a8776.png)

Should we do something differently to show [multiple polygons](https://user-images.githubusercontent.com/7581631/196653320-f967a3ab-62d8-488c-9d39-086854c395df.png) in polystat panel?

**Comment by tolzhabayev** [comment]
@nidhisht could you try the `2.0.4` version, it should have this issue fixed https://github.com/grafana/grafana-polystat-panel/pull/246

**Comment by nidhisht** [comment]
Thank you, @tolzhabayev.  Its working fine with polystat panel version 2.0.4.
