### ISSUE TITLE
upgrading polystat panel to 2.0.1 removes global thresholds

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana-polystat-panel#241]
**Summary of Issue:**

Customer upgraded from Grafana 8.5.5 and Polystat Panel 1.2.8 to Grafana 9.2.0 and Polystat 2.0.1. When they did so, they noticed that instead of being green, grey and orange, their hexes were all blue. 

**Grafana Version:** 8.5.5 (previous) -> 9.2.0 (current)

**Support Investigation:**

After receiving the panel JSON and panel DataFrame JSON from the customer, I reproduced the working environment with v8.5.5 + polystat 1.2.8. I then upgraded the instance, but did not upgrade the plugin, and nothing changed. After upgrading the plugin to 2.0.1, the global thresholds values were removed. I'm assuming this is because of the change to react as of polystat 2.0.0, which includes a migration to the new config schema. I confirmed that staying on 1.2.11 prevents the issue, and that you can re-add the global thresholds as a short term workaround. However, this workaround isn't scalable.

**Steps to reproduce (if possible):**
- Use not-working panel json and panel dataframe to re-create panel on an instance with a 1.2.X version of Polystat panel.
- Observe the global thresholds / hex colors.
- Upgrade the polystat panel to 2.0.X version.
- Observe that the hex colors are now reset to uniformly being blue, and that global thresholds values are absent from panel JSON.

**Comment by briangann** [comment]
Fixed by release v2.0.3
