### ISSUE TITLE
Issues when working with certain datasources after upgrade

### ISSUE THREAD

**Issue by blauter** [grafana/grafana-polystat-panel#242]
I have been trying to re-create all my polystat panels that broke when upgrading to Grafana 9.1 and latest plugin version and having trouble with all my postgres/snowflake/mssql data sources. I can't seem to get the data in a format that plays nice with polystat.

In previous version (Grafana 7/8 with older plugin), this query would create one polygon per device type but now its only displaying one.
![2022-10-20_09-03-20](https://user-images.githubusercontent.com/18193005/196957833-6d6d7bd4-6c7b-4aec-913a-98c73e5a67f6.gif)

Here is how my data is returned. I tried formatting as table, adding reduce expression/transformation as well as some other transformations and I just can't seem to get it to work.
![2022-10-20_09-04-37](https://user-images.githubusercontent.com/18193005/196957849-f4a7881f-15b3-40aa-bd6b-4b3a4f289245.gif)

In old dashboard, my working composite metric would be something like:
PARSINGFAILPERCENT ${device_type}

I actually had a similar issue with InfluxDB but worked around it by renaming measurement to include device name. 
from(bucket: "mybucket")
 |> range(start: -30m)
 |>filter(fn: (r) => r["_measurement"] == "DelayByDevice")
 |> map(fn: (r) => ({
        _value: r._value, 
        _time: r._time, 
        _measurement: "DelayByDevice6h - ${r["device_type"]}"
    }))

**Comment by blauter** [comment]
I am guessing this may be due to lack of dataframe support. If I add below transformations, I can get it to work, however, it breaks every single other query from influxdb and prometheus since I am in mixed mode and it doesnt appear transformations can be applied to specific queries.

1. Prepare time series -> Multi-frame time series
2. Labels to fields -> mode "Columns", Labels "DEVICETYPE"

Is there any potential work around for this that I can try?

**Comment by Teofaness** [comment]
The same problem with zabbix data-source.

**Comment by Teofaness** [comment]
![image](https://user-images.githubusercontent.com/87394630/197594807-087cb25e-f66e-4ce0-90fd-8713a5cd0081.png)
![image](https://user-images.githubusercontent.com/87394630/197594855-31410e9e-239d-4d82-b794-3ba954ccc2d5.png)

**Comment by briangann** [comment]
I'll have a fix for this shortly - this is a problem with datasources that are sending "narrow" vs "wide" dataframes, and the new plugin is not handling both cases. 

Noticed this with the CSV (non-metric) test datasource, the metric-csv option works correctly.

**Comment by briangann** [comment]
fix was included in the latest release, re-open if you still run into a problem with the new version.

thanks!
