### ISSUE TITLE
Dashboard variables and composites don't work (ver 2.x)

### ISSUE THREAD

**Issue by a-mazed** [grafana/grafana-polystat-panel#247]
I have a dashboard with a lot of polystat panels, that use composites. Those composites use variables for name and metrics.

![image](https://user-images.githubusercontent.com/25726917/200842037-3f3879f6-69f6-4261-a2a7-89b916f26c92.png)

It works in the combinations:
- Grafana 8.x + Polystat 1.2.11
- Grafana 9.2.3 + Polystat 1.2.11

But with Polystat 2.x it doesn't work. 
What is the problem? How can I fix it?

https://github.com/grafana/grafana-polystat-panel/issues/247#tasklist-block-72bf0761-00ae-48d2-92df-673c63718ad8

**Comment by briangann** [comment]
Just to double check - are these template variables or variables from a query?

**Comment by a-mazed** [comment]
These are dashboard variables
![image](https://user-images.githubusercontent.com/25726917/200863388-63b5ed29-b6f8-43d2-91f7-e7d29eb7f6da.png)
![image](https://user-images.githubusercontent.com/25726917/200863609-6af4ecea-41f8-49c4-8a07-ade694e082d6.png)

**Comment by briangann** [comment]
ok perfect, will have a fix shortly.

**Comment by briangann** [comment]
The fix for this will be included in v2.0.4, additional testing is needed before releasing it.

**Comment by a-mazed** [comment]
Now it works with version 2.0.4
Thank you very much!

**Comment by briangann** [comment]
welcome - let us know if you run into any other issues!
