### ISSUE TITLE
PolyStat panel not showing up (2.0.4)

### ISSUE THREAD

**Issue by rkoemecs** [grafana/grafana-polystat-panel#249]
With Grafana v9.2.0 PolyStat 2.0.4 panel in most cases is not showing up. DIV element where polystat should be located is empty, only resize symbol is visible. Sometimes after multiple hard refreshes (Shit+Ctrl+R) it appears. If I add any new panel to dashboard, then also PolyStat become visible.
![polystat](https://user-images.githubusercontent.com/65662199/202252839-9a3b9e95-2e9e-4bf7-bf5b-00c7c21e501b.png)

**Comment by Espe0n** [comment]
Can confirm the Bug on Grafana 8.5.14 with PolyStat 2.0.3
![image](https://user-images.githubusercontent.com/39615557/202395591-0e8fc017-e94b-4bf6-8057-17da81310219.png)
Exact the same behavior. When adding a new Panel, the missing Panel shows up.
Diff of the Json-Modell shows no difference and after saving and reloading the Dashboard the Panel is gone again.

**Comment by CoreMoni** [comment]
We had the same issue.

**Comment by btarazonaj** [comment]
Check if pluginVersion value in the Json Model are the same of your polystat plugin version. I had to change it manually from 2.0.2 to the current version and when save dashboard it loads again.

**Comment by rkoemecs** [comment]
@btarazonaj thanks for workaround, this helped me! In my dashboard I had `"pluginVersion": "2.0.1"`

**Comment by btarazonaj** [comment]
@rkoemecs The problem is that it is not a long-term solution, every time the plugin is updated you will have to manually change the version in all dashboards. Try to mark this issue as a bug

**Comment by rkoemecs** [comment]
Sure it's not long-term solution. Looks like only project owners can add labels.

**Comment by btarazonaj** [comment]
@rkoemecs Uhhh okay. If helps... I detected the problem since polystat v2.0.2(updating from v2.0.1) + grafana v9.1.7

**Comment by chrisharbro** [comment]
Hi y'all, I'm part of the Grafana Labs support team, thanks for reporting the issue! I've added the `bug` label. We had a customer write in last week with the same issue and the short-term fix of manually adjusting the panel JSON worked in his case as well, so this seems to be a decent workaround until further investigation is done by the dev team to identify and fix the core issue.

As we can see from the dashboard JSON, the plugin version is 2.0.4:
```
    {
      "type": "panel",
      "id": "grafana-polystat-panel",
      "name": "Polystat",
      "version": "2.0.4"
    },
```
 
and in the panel JSON, it is listed as being 2.0.1:
```
     "type": "grafana-polystat-panel",
      "title": "Reproduced with embedded data",
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "pluginVersion": "2.0.1",
```

Manually updating pluginVersion in the panel JSON allowed for the panel to render successfully.

**Comment by briangann** [comment]
this looks like a bug in the migration code - it should not be storing the version of the plugin inside the panel/dashboard.
