### ISSUE TITLE
Polystat composite gets split on different cells when using multiple Var's.

### ISSUE THREAD

**Issue by Rafjt** [grafana/grafana-polystat-panel#250]
Hi, I have an issue when using the polystat plugin. Basically I'm trying to show some values of a DB in my case cpu, memory, connections and burstbalance and the graph works perfectly for a single DB but when I try to view multiple or all the DB's the different values are getting splitted on different cells.

<img width="1792" alt="Capture d’écran 2022-11-24 à 17 51 19" src="https://user-images.githubusercontent.com/118538315/203835263-00df5bb0-1fbc-4200-b99e-225c32439e49.png">

<img width="1792" alt="Capture d’écran 2022-11-24 à 17 52 24" src="https://user-images.githubusercontent.com/118538315/203835279-258b7bc0-1036-4a6f-8b02-ad9f3d489490.png">

Grafana plugins: Polystat 2.0.4

**Comment by ThierryH** [comment]
Hello 
We have exactly the same issue , grouping works fine for a single element  selected , but when there is more than one element selected the grouping of indicators does not occurs and they are spread over multiple cells.
Grafana 9.2.6
polystat 2.0.4
Datasource Prometheus 

Question how the plugin works in case of multiple selection ? 
Let s say we have a templace variable with 3 values selected.  The content of the variable is then (valueA|valueB|valueC) 
   Is there an iteration over the different values to build the regexp to match the metrics for each specific value:
       valueA => build the composite name and  metrics regexp for valueA
       valueB => build the composite name and  metrics regexp for valueB
       valueC => build the composite name and  metrics regexp for valueC

  or the polystat panel use and inject the whole value  (valueA|valueB|valueC) and we need to take that into account into the regexp and composite name ?

Thanks in advance

**Comment by briangann** [comment]
I think the multiple selection is not working as intended - can you compare v1 to v2 with your setup and see what it does.

I'll try the multi-select also and compare the results from v1/v2. 

The intention is as you described - iterate over the different values of the template variable and build the regex then match metrics.

**Comment by ThierryH** [comment]
Hello Brian , 
I will test the V1 next week and share the result , or as you have qualified as a bug you don't need me to test it ?
Thanks

**Comment by Rafjt** [comment]
Issue resolved since [this commit](https://github.com/grafana/grafana-polystat-panel/pull/270) thanks a lot !
