### ISSUE TITLE
Polystat - Adding more polygons than the limit should be handled better

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana-polystat-panel#255]
When adding more than 100 polygons on a polystat panel using the default 100 display limit, an error "Cannot read properties of undefined (reading '0')" is shown in the UI

**Error in browser console:**
```
TypeError: Cannot read properties of undefined (reading '0')
    at A (Polystat.tsx:232:37) 
    at eval (Polystat.tsx:389:28)
    at Array.map (<anonymous>)
    at fo (Polystat.tsx:388:35) 
    at ra (react-dom.production.min.js:157:137)
    at Ws (react-dom.production.min.js:267:460)
    at Ou (react-dom.production.min.js:250:347)
    at ku (react-dom.production.min.js:250:278)
    at Eu (react-dom.production.min.js:250:138)
    at vu (react-dom.production.min.js:243:163)
```

CalculatedPoints is limited by “layoutDisplayLimit” whereas options.processedData is not.

https://github.com/grafana/grafana-polystat-panel/blob/20fdd95d09fe060dbadc00d4504468ebba5620c3/src/components/Polystat.tsx#L171

When processedData has more entries than the layoutDisplayLimit and the map function calls getCoords(index), this causes an exception when reading an index out of the range.

https://github.com/grafana/grafana-polystat-panel/blob/20fdd95d09fe060dbadc00d4504468ebba5620c3/src/components/Polystat.tsx#L388-L389

https://github.com/grafana/grafana-polystat-panel/blob/20fdd95d09fe060dbadc00d4504468ebba5620c3/src/components/Polystat.tsx#L231-L235

**Steps to reproduce:**

- Add Polystat panel to a dashboard
- Set TestDataDB datasource using value 101 for series count (default polystat display limit is 100)
- See "Cannot read properties of undefined (reading '0')" error in UI and browser console

**Comment by mbrancato** [comment]
Thanks for opening this ticket. the workaround was unclear, but this helped me. For others, the workaround on the panel options under layout is to increase the display limit.

**Comment by thenodon** [comment]
Just leave it unset seems to work and implicit mean unlimited - tested in 2.0.7
![image](https://user-images.githubusercontent.com/3584946/231176708-bc086480-2a18-4ad0-a23c-646a2e71b86a.png)
