### ISSUE TITLE
Global override editor displays "Value" instead of labels/metric names for some queries

### ISSUE THREAD

**Issue by briangann** [grafana/grafana-polystat-panel#256]
For some queries the labels are not recognized as metric names, and the global overrides do not display them as expected:

A query like this:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/7364245/221677826-aecf0f37-5ade-4094-9f7e-cdf7d006f906.png">

Results in this polygon:

<img width="175" alt="image" src="https://user-images.githubusercontent.com/7364245/221677747-82c9f848-12b5-4aea-baf4-f00ecfd14281.png">

And when adding an override, the editor displays this:

<img width="186" alt="image" src="https://user-images.githubusercontent.com/7364245/221678018-ff58841c-666d-4ab5-85bd-4cc0615bf113.png">

**Comment by BryanHunt** [comment]
Does this also fix the same issue with selecting metrics in a composite?  Also, is there an ETA for a release with this fix?

**Comment by BryanHunt** [comment]
Awesome!  Thanks.
