### ISSUE TITLE
Composite not working

### ISSUE THREAD

**Issue by BryanHunt** [grafana/grafana-polystat-panel#262]
I just picked up 2.0.5 and I'm still having problems getting composite to work.  The data is from node-exporter and I'm trying to composite the overall cpu usage with memory used per instance (host).  The two queries are (these came from the node exporter dashboard on grafana.com):

```
(sum by(instance) (irate(node_cpu_seconds_total{mode!="idle"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))) * 100

100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)
```

These two queries correctly display the individual values for CPU and memory per node, but when I try to add a metric in the composite, the only selection available is a single "Value" option.  Selecting "Value" did not work.

I tried naming the queries and using those name, but that didn't work either.  Maybe it's just my lack of understanding that I haven't been able to figure out what to put into the Metric/RegEx box based on the documentation available.

**Comment by briangann** [comment]
let me look into this - should be able to reproduce it with what you specified above

**Comment by Ruppsn** [comment]
Hello,

we have identical metrics and the same Problem.
In Composite there is only the Value option. I am not able to get it to work. 

Grafana: 9.4.7
Plugin: 2.0.7

Is there maybe a Documentation with more Detail. Not sure if i am the problem here 😓

**Comment by BryanHunt** [comment]
I just picked up version 2.0.8 and I'm still having a problem with the composite not working.  I've set it up as shown in the screenshot below.  I get both metrics displayed, but as individual cells instead of a composite by hostname (instance).  Am I just not understanding how to add the metrics to the composite?



<img width="3334" alt="Screenshot 2023-05-28 at 8 16 04 AM" src="https://github.com/grafana/grafana-polystat-panel/assets/504299/8393cc74-d2d8-4eae-b1ad-d2606b8633fe">

**Comment by briangann** [comment]
there's still a bug - 2.0.8 was to fix an edge case, but the problem exists for other datasources. I'm working on a more generic method to provide metric hints and hopefully add it to one of the general packages.

i see the same results as you do with my prometheus queries - right now the regex option is the only "safe" method to match metrics in composites.

(targeting a release on Wednesday as long as testing goes well with the new method)

**Comment by BryanHunt** [comment]
Can this be re-opened?
