### ISSUE TITLE
crash when trying to create override

### ISSUE THREAD

**Issue by larsf** [grafana/grafana-polystat-panel#265]
This is on grafana 9.3.6 with polystat plugin version 2.0.5 and static plugin version 2.1.0

I tried to follow your tutorial, but used the "static plugin" for datasource (it may be the issue is related to that). Created a panel with two metrics in it (both numerical, both with a single value). That displays fine, but when I got to the polystat options to add overrides I get this:

`An unexpected error happened
TypeError: undefined is not an object (evaluating 'n.labels.__name__')

j@
div
div
div
Collapse@http://localhost:3000/public/build/519.59a9a42744951a01f708.js:251:322
I@
div
div
p@http://localhost:3000/public/build/519.59a9a42744951a01f708.js:1406:318
div
div
@http://localhost:3000/public/build/519.59a9a42744951a01f708.js:6487:18150
div
div
div
t@http://localhost:3000/public/build/7601.064cc75d586bff6ad076.js:2:711573
p@http://localhost:3000/public/build/519.59a9a42744951a01f708.js:424:3321
div
div
Kn@http://localhost:3000/public/build/DashboardPage.f2fed3c5febf77f94f4d.js:135:4520
div
div
Ii@http://localhost:3000/public/build/DashboardPage.f2fed3c5febf77f94f4d.js:258:149
div
n@http://localhost:3000/public/build/DashboardPage.f2fed3c5febf77f94f4d.js:37:6456
div
n@http://localhost:3000/public/build/DashboardPage.f2fed3c5febf77f94f4d.js:37:8405
_t@http://localhost:3000/public/build/DashboardPage.f2fed3c5febf77f94f4d.js:37:13995
div
div
div
b@http://localhost:3000/public/build/519.59a9a42744951a01f708.js:5799:1232
ya@http://localhost:3000/public/build/DashboardPage.f2fed3c5febf77f94f4d.js:381:1381
Connect(ya)@http://localhost:3000/public/build/7601.064cc75d586bff6ad076.js:2:1042443
WithTheme(Connect(ya))
Er@http://localhost:3000/public/build/DashboardPage.f2fed3c5febf77f94f4d.js:504:7184
DashboardPage
Connect(DashboardPage)@http://localhost:3000/public/build/7601.064cc75d586bff6ad076.js:2:1042443
Suspense
c@http://localhost:3000/public/build/519.59a9a42744951a01f708.js:1207:307
_c@http://localhost:3000/public/build/519.59a9a42744951a01f708.js:8831:350
t@http://localhost:3000/public/build/7601.064cc75d586bff6ad076.js:2:1060838
t@http://localhost:3000/public/build/7601.064cc75d586bff6ad076.js:2:1062859
main
Cd@http://localhost:3000/public/build/519.59a9a42744951a01f708.js:8792:6841
t@http://localhost:3000/public/build/7601.064cc75d586bff6ad076.js:2:1057455
div
o@http://localhost:3000/public/build/519.59a9a42744951a01f708.js:1996:4312
@http://localhost:3000/public/build/7601.064cc75d586bff6ad076.js:2:271047
l@http://localhost:3000/public/build/519.59a9a42744951a01f708.js:6143:19563
c@http://localhost:3000/public/build/519.59a9a42744951a01f708.js:1207:307
u@
l@http://localhost:3000/public/build/7601.064cc75d586bff6ad076.js:2:1040486
Su@http://localhost:3000/public/build/519.59a9a42744951a01f708.js:8844:120`

This happens if I just scroll down and use the override functionality on the bottom of the option panel on the right. If I instead click on the override tab on the top-right, I don't get a crash, but I am only allowed to override values

**Comment by briangann** [comment]
will investigate this, thanks for the bug report!

**Comment by Dgarc359** [comment]
This also occurs with composites when adding metrics for the composite on v2.0.5

Setup to replicate:
Panel: Polystat panel v.2.0.5
Datasource: TestData (alias to "data")
 - Scenario: Grafana API
 Transform: Extract fields
 - Format: JSON
 
 Once this is set up, clicking 'add metric' to the composite will cause 'TypeError: n.labels is undefined' to be thrown.
 
This same setup in v.2.0.4 will not cause the panel to break.

**Comment by briangann** [comment]
will have the fix published today, PR is in progress
