### ISSUE TITLE
Migrate away from tippyjs-react

### ISSUE THREAD

**Issue by academo** [grafana/grafana-polystat-panel#271]
Currently polystat shows tooltips using [tippyjs-react](https://github.com/atomiks/tippyjs-react/) which while testing the new plugins sandbox didn't work well.

We should migrate away from the library and perhaps use another library or implement the tooltips directly inside the plugin.

**Comment by briangann** [comment]
given how the tooltips are behaving now, it would be great to find a sandbox friendly solution.

**Comment by briangann** [comment]
tooltips were migrated over to use react-tooltips
