### ISSUE TITLE
Polystat Crashes on Hover with Repeat Rows

### ISSUE THREAD

**Issue by bryandicarlo** [grafana/grafana-polystat-panel#288]
# Issue
When hovering over a polystat panel that is repeated via a repeat row variable, the polystat panels in other rows crash.

## Before Hovering:
![image](https://github.com/grafana/grafana-polystat-panel/assets/24595381/b66d2b40-6b9e-4dde-b13f-3dd4b8c2a7d3)
## After Hovering:
![image](https://github.com/grafana/grafana-polystat-panel/assets/24595381/21682e92-7a8b-4e1d-b297-f9d0133ecd46)
The admonition displays the following error: "Cannot read properties of undefined (reading 'color')"

![image](https://github.com/grafana/grafana-polystat-panel/assets/24595381/a3b0de60-0238-4101-b396-eb2ea98a2466)

Grafana Version: v10.0.1
Plugin Version: v2.1.0

**Comment by briangann** [comment]
Definitely a bug, and was not covered in the tests.  

Will fix and add a dashboard that exercises this type of setup to verify.

**Comment by majerus1223** [comment]
Happen to have any timing as to when this might be fixed, is this only an issue in 2.1.2? thanks!

**Comment by phantazia** [comment]
as a workaround, you can disable the tooltip to avoid the issue

**Comment by stavr666** [comment]
Got similar issue after upgrading Grafana to 10.1.0 and plugin to 2.1.2. Tooltips now not flickering, but secondary panel crashing after hoovering on first:
![image](https://github.com/grafana/grafana-polystat-panel/assets/84839985/7077af29-f1f8-48b4-bed5-70c754104b6f)

Also, for some reason tooltips on instable panel stacking with tooltip form first panel:
![image](https://github.com/grafana/grafana-polystat-panel/assets/84839985/712728f9-477f-4f08-888f-06790aa28730)

**Comment by dmgeurts** [comment]
> as a workaround, you can disable the tooltip to avoid the issue

Thank you for the workaround, just encountered this issue today.
