### ISSUE TITLE
Polystat hangs with more than 20 polygons

### ISSUE THREAD

**Issue by briangann** [grafana/grafana-polystat-panel#294]
rendering large data sets on G10 is causing the browser to hang. This may be a side effect of tooltip changes, since 2.0.9 on G9 with same setup works fine.

Specifically this is a bug due to the "Display Limit" being set to 100, and if the amount of items to be rendered exceeds this value, it should be giving a warning.  Currently it just hangs for a long time then displays:

<img width="191" alt="image" src="https://github.com/grafana/grafana-polystat-panel/assets/7364245/986f993f-112c-43bd-95dc-2f4f27f6b2df">

This can be reproduced using the test data source, and random walk with 150 series.

With a higher limit (setting it to 300) that produces 150 series, the performance is still poor.  It does not appear to be a rendering issue, but a raw data-processing issue.

Additional processing improvements are needed to make the plugin more usable with large amounts of polygons to be rendered.

**Comment by tolzhabayev** [comment]
I also do not get a warning when Series count is > than Display Limit in 9.5.6 but rather the same:
https://user-images.githubusercontent.com/7364245/258005556-986f993f-112c-43bd-95dc-2f4f27f6b2df.png

**Comment by briangann** [comment]
hang fixed by PR #295, will fix the warning issue in another PR
