### ISSUE TITLE
Cannot read properties of undefined (reading 'color') tooltips

### ISSUE THREAD

**Issue by menvol3** [grafana/grafana-polystat-panel#307]
After updating to the latest available plugin version we encouraged problems with our Dashboards 

`cannot read properties of undefined (reading 'color') tooltips`

When a dashboard is loaded for the first time it looks like all things are normal until you try to scroll your page up and down, after that issue can be reproduced.

<img width="451" alt="Screenshot 2023-09-08 at 12 53 07" src="https://github.com/grafana/grafana-polystat-panel/assets/28445642/ca5dad8b-b840-4972-aede-163e8db3f8cf">

What is strange is that it appears sporadically and also can disappear in the same way, to 100% fix it, the Show tooltips option can be disabled, but it is not a good way.

Our Grafana version is 9.4.7

**Comment by Ukochka** [comment]
Should be fixed by https://github.com/grafana/grafana-polystat-panel/pull/311

**Comment by briangann** [comment]
v2.1.3 just released, includes fix for this issue.  Reopen if you see it re-occur.
