### ISSUE TITLE
polygon titles incorrect

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana-polystat-panel#309]
I recently updated polystat plugin from 2.0.5 to 2.1.2 and the behaviour in how polygons are titled has changed. 

I have a dashboard that uses is to display 4 vaules form a SQL query.
```
"severity","count"
medium,3
critical,0
high,0
low,0
```
With 2.0.5, the 4 boxes has the titles of the first column, and the value of the 2nd column. 
Now with 2.1.2, the title for each box is "count medium" 
So, it's including the name of the 2nd column in the title, and it's also repeating the first value of the first column across every box.
 
![image](https://github.com/grafana/grafana-polystat-panel/assets/8004654/764a280f-c4af-4d9d-bf8f-0da3c8f8c77c)

The expected behaviour is that column 1 is used as the title, and column 2 as the value (this is how it worked in 2.0.5

**Comment by briangann** [comment]
This was a side-effect of a couple of changes.  The performance issue with a deep clone on circular frame data plus a method setting values in a "get" call.

The fix returns the plugin to the previous behavior and includes a new test to check for it in the future.
