### ISSUE TITLE
Color rendering fails in Safari

### ISSUE THREAD

**Issue by briangann** [grafana/grafana-polystat-panel#31]
Safari doesn't render the polygon fill color (everything is black)

**Comment by VitaliyBreslavskyi** [comment]
Hi @briangann !

Is this expected that I'm still getting all-black in Safari?

With best regards,
Vitaliy

**Comment by VitaliyBreslavskyi** [comment]
Hi @briangann !

Is this expected that I'm still getting all-black in Safari?

With best regards,
Vitaliy

**Comment by briangann** [comment]
Did it previously show all-black in Safari?

The recent update may have removed the workaround for it, will test and verify.

**Comment by VitaliyBreslavskyi** [comment]
Yes, and it seems that this issue is back, screenshot how it looks:

![Screen Shot 2020-01-27 at 10 43 11 AM](https://user-images.githubusercontent.com/59922095/73160533-f16d7580-40f1-11ea-9a24-c366ef9112cc.png)

Thank you for looking in to it!
