### ISSUE TITLE
Tooltip shows adjacent panel values when we have multiple panels with polystat on same dashboard

### ISSUE THREAD

**Issue by sunilthemaster** [grafana/grafana-polystat-panel#314]
We have created Grafana dashboard which contains multiple panels with polystat plugin.

When we hover over any metric, on tooltip, it shows data of other panel.

Instead of showing data for 4th column 1st row box in panel 1, its showing data from panel2, 4th column 1st row.
<img width="1423" alt="image" src="https://github.com/grafana/grafana-polystat-panel/assets/5255193/1674ebd2-c87e-414f-8783-575f258d381f">

Version: 2.1.3

**Comment by DarkPsionix** [comment]
I have the same kind of issue, but in my case I have a polystat panel with "Repeat Options" activated.

![image](https://github.com/grafana/grafana-polystat-panel/assets/65708874/99d3413a-8324-4aeb-bdc0-1f84fcf22dae)

**Comment by sunilthemaster** [comment]
Awesome, thanks a lot @briangann for taking up the issue on priority. Really appreciate!
Waiting for PR merge :)

**Comment by sunilthemaster** [comment]
Thanks a lot for quick fix. I confirm, changes are working as expected :)
