### ISSUE TITLE
Overlapping tooltips

### ISSUE THREAD

**Issue by TioVinaMatos** [grafana/grafana-polystat-panel#315]
Hello, in version 2.1.2 the panel continues to have overlapping tooltips as shown in the image. (translate PTbr to English via Google)

![image](https://github.com/grafana/grafana-polystat-panel/assets/92754226/2e250491-3092-40d2-83cd-35edebeba952)

**Comment by sunilthemaster** [comment]
duplicate to https://github.com/grafana/grafana-polystat-panel/issues/314

**Comment by TioVinaMatos** [comment]
The problem persists in version 2.1.3 as follows:

![image](https://github.com/grafana/grafana-polystat-panel/assets/92754226/070aad0e-dde8-4424-9a05-b31289d9d9c2)
![image](https://github.com/grafana/grafana-polystat-panel/assets/92754226/f4601a49-667a-48e0-8a9a-2ac47fe8fdd9)

Thank you for helping.

**Comment by briangann** [comment]
We're working on a fix for this and expect a release by EOD.  Thanks for reporting the issue!
