### ISSUE TITLE
Plugin show "no data" even when there is data returned from the query

### ISSUE THREAD

**Issue by kgeorga** [grafana/grafana-polystat-panel#332]
Hello, I am trying to use this plugin with Cloudwatch metrics, specifically AWS/EC2 metrics returned from some instances and even though I can see data returned from the query when switching to table view the visualisation shows nothing and when I resize the panel it shows "no data". Grafana version is 10.1.2 and I just use the default settings for the visualisation. It seems to me that this should work straight forward out of the box with some simple CPU metrics returned but I think I'm missing something. Is there anything else we need to do for this plugin to work?

**Comment by briangann** [comment]
there was a bug with a large number of metrics causing issues that was fixed in v2.1.5, can you try that version and let me know if you still see a problem?  if you have any data/snapshots/screenshots to share i can debug further.

**Comment by briangann** [comment]
the cloudwatch datasource option to use table data hasn't been tested, the plugin is expecting dataframes for metrics. will check and see if there is a way to support table-based data (converting to dataframes as needed)
