### ISSUE TITLE
Help with formatting

### ISSUE THREAD

**Issue by lonelyadmin** [grafana/grafana-polystat-panel#343]
Not sure if this is a me issue, grafana issue, or polystat thing. Likely me.

I'm using polystat to draw a representation of switch interfaces from a prometheus datasource. Simple up/down type setup that also shows the interface name and alias. I'm currently doing this by adding {{ifName}}{{ifAlias}} in the Options->Legend field. Is there any way to insert a new line in the rendered HTML? I have the grafana sanitize html off, but `<p>` or `<br />` seem to be ignored. Anything rendered in the `<text>` tag seems to be rendered as text...which is likely by design.

Is there any way to insert a newline between these values? I'm obviously not a pro at this, so not sure how to proceed.

Thanks for your time.

![polystat](https://github.com/grafana/grafana-polystat-panel/assets/33500076/0c63b9d4-6c2c-4c4f-9d5e-0d9af5178ee2)

**Comment by lonelyadmin** [comment]
Found a few references, but still not sure if this is a polystat issue, or something with grafana or prometheus.

https://community.grafana.com/t/formatting-legend-format/80671/3

https://community.grafana.com/t/formatting-legend-format-for-graph-table/758

**Comment by briangann** [comment]
There's no multi-line support right now for polystat, but it is a planned feature.  I'd really like to have it also.

**Comment by briangann** [comment]
Related to #277
