### ISSUE TITLE
Weird tooltips/composite behavior

### ISSUE THREAD

**Issue by maciejlesny** [grafana/grafana-polystat-panel#355]
Hi,
I noticed strange behavior of composite elements after updating from plugin version 1.2.11 to version 2.0+. Everything is shown in the attached gif. The green entries should not be visible at all, on hover I expect only the orange value to be displayed (as it was in version 1.2.11 and earlier).

![Animation](https://github.com/grafana/grafana-polystat-panel/assets/92303536/09d0e4e6-99da-4160-9a5e-132d482f19ca)

**Comment by briangann** [comment]
looks like a regression, will investigate and release a fix. tooltips did undergo a large rewrite when the plugin was migrated to React.
