### ISSUE TITLE
Polystat variables not being replaced in the default clickthrough field

### ISSUE THREAD

**Issue by alwaysshrek** [grafana/grafana-polystat-panel#356]
In v2.1.7, the polystat variable ${__cell_name} (& probably others) that are defined in the 'Default clickthrough' field are not being replaced with the needed value. I remember this working in the previous versions, although I don't know the exact version this stopped working. I also don't have admin privileges on my grafana instance to try to figure out which version actually broke it.

![image](https://github.com/grafana/grafana-polystat-panel/assets/499593/ee49857e-c5dd-408c-94da-ce34ed0e4b77)

**Comment by briangann** [comment]
confirmed this is a bug, will have a fix for it in the next hour

**Comment by briangann** [comment]
fixed in v2.1.8, thanks!
