### ISSUE TITLE
Tooltip displaying non triggered values when it should not based on thresholds

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana-polystat-panel#368]
When the tooltips display mode is set to only show triggered values there are cases where the panel is still showing the "OK" values as defined by the threshold. I've attached a simple example of where this is working as expected. To see case where it is not working see [this escalation](https://github.com/grafana/support-escalations/issues/10080) 

https://github.com/grafana/grafana-polystat-panel/assets/22381771/d68d537e-3225-4c0c-a718-d1fb55b6471c

[Poly stat test-1713359442192.json](https://github.com/grafana/grafana-polystat-panel/files/15011470/Poly.stat.test-1713359442192.json)

**Comment by Jwhite7777** [comment]
Any updates on this issue?

**Comment by briangann** [comment]
> Any updates on this issue?

a fix is in progress, expect to have a new release today
