### ISSUE TITLE
Add support for Numerical Sorting

### ISSUE THREAD

**Issue by MartinRoenneburg** [grafana/grafana-polystat-panel#37]
I want to use the polystat panel to show up / down states of a matrix system.
My problem:  The matrix index counts 1-9,10,11 ...

The Polystat Panel shows ...
1,10,11 ... 19,2,20, ....

It would be nice to have the numerical sort option like in Grfana Variables.

**Comment by briangann** [comment]
Will add a better sort method, I see the same issue.

**Comment by briangann** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Polystat](https://trello.com/c/wmYFqPP9/1-polystat)

**Comment by briangann** [comment]
this is in progress, will have a new release in a few days

**Comment by briangann** [comment]
this one slipped, targeting a small release end of week for this issue and a couple others.
