### ISSUE TITLE
allow passing the series name into the clickThrough url

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana-polystat-panel#38]
It would be nice to be able to have the clickThrough url link to another dashboard and pass through a template variable value in the url.

eg, have a polystat panel that shows the load of all servers.  When clicking on a polygon for a specific server, the user should be redirected to a "server metrics" dashboard that shows detailed stats for the server.

**Comment by briangann** [comment]
implemented and released.

Details on how to use it here: https://github.com/grafana/grafana-polystat-panel#templating
