### ISSUE TITLE
"Show Value" turned off does not hide value for certain queries

### ISSUE THREAD

**Issue by Mesona** [grafana/grafana-polystat-panel#383]
I am messing around with polystat and am trying to get just the metric name, without the value, showing. In this query, when I turn "Show Value" to "off" nothing changes.

![Screenshot 2024-05-17 at 4 21 06 PM](https://github.com/grafana/grafana-polystat-panel/assets/4132646/beafc08f-c904-476d-8a97-571c292f50cd)

However, with this query, the option functions perfectly well:
![Screenshot 2024-05-17 at 4 31 06 PM](https://github.com/grafana/grafana-polystat-panel/assets/4132646/93ef5d23-586d-4df3-8287-e159a52de147)

![Screenshot 2024-05-17 at 4 31 14 PM](https://github.com/grafana/grafana-polystat-panel/assets/4132646/7e0bc171-6dd3-4969-af86-7106f18da819)

I am new to grafana, so this might be expected behavior, but to me this seems like a bug.

**Comment by briangann** [comment]
it is a bug, a fix is in progress, thanks for the report!

**Comment by Mesona** [comment]
I deleted my dashboard and recreated and do not see this problem anymore.

**Comment by briangann** [comment]
i did reproduce it also, working out some final changes to the code before releasing a new version.
