### ISSUE TITLE
after upgrading to version 2.1.12  "r.get is not a function"

### ISSUE THREAD

**Issue by dequeee** [grafana/grafana-polystat-panel#398]
Hi,

I had previously opened an issue for version 2.1.11, where in any dashboard the error "l. add is not a function" was shown. After upgrading to the latest version where the problem was resolved, another one appears:

"r.get is not a function"

in the table format view the data appear, while the error is in the graphical view of the panel.

Are you aware of this problem?

Thanks!

**Comment by galsilb** [comment]
Same here. Broken after update.
Eveything worked perfectly before that.

**Comment by briangann** [comment]
which version of Grafana?  there were some api changes that triggered the .add issue, might be something with r.get now.

i'll run it through all of the versions and see if i can reproduce it in the meantime.

**Comment by galsilb** [comment]
@briangann I'm running grafana 9.3.6
If updating to latest grafana works, ill do that...

I can't seem to find the polystat version I was using before that.

**Comment by galsilb** [comment]
@briangann Also, It happens with SQL based data source.
Something with the data as a table and not as a timeseries causes that.

**Comment by dequeee** [comment]
Hi,

I'm running Grafana 9.2.10. I also have a server where is installed the version 9.5.19.

Do you thinks this bug needs a new patch to be fixed?

Thanks

**Comment by galsilb** [comment]
After upgrading to grafana version 11.1.0, everything works fine again.

**Comment by dequeee** [comment]
Hi,

Any update for the fix on Grafana version 9?

**Comment by dequeee** [comment]
Hi,

Any update?

**Comment by dequeee** [comment]
There are few things to edit after upgrading.

Grafana 11.1 only load polystat 2.0.0 >, so you have to upgrade also polystat panel.

Upgrading from panel polystat version 1.12.x to 2.1.x requires few changes in complex dashboards.

Upgrading a panel with complex overrides and composites requires to add / at the start and at the bottom of the metric, which before wasn't required.

So this problem with metrics can lead to increasing the number of cells. which also lead to an error:

Cannot read properties of undefined (reading 'x')

if the number of cells excedes the limit configured in the layout section.

Metrics changes also afflicts cells colors. i found out that now sometimes value mapping conflicts with overrides. so i used value mapping color setting for the cells color configuration instead of overrides.

I hope this could be useful.
