### ISSUE TITLE
Add support for Value Mappings

### ISSUE THREAD

**Issue by zegelin** [grafana/grafana-polystat-panel#42]
This plugin is almost perfect for displaying the service status of a bunch of systems. Except that it can only display a numeric value.

It would be nice to be able to map values (or value ranges) to textual values, similar to the _Singlestat_ plugin and its _Value Mappings_ options.

For example, a metric that represents service status with a value between 0 and 1, could then be mapped to:
0 = "Down"
.1 - .9 = "Unreliable"
1 = "Up"

**Comment by briangann** [comment]
sounds like a great enhancement to me.  the value mapping is empty/not implemented currently.

**Comment by ortizleo** [comment]
+1 Plz
