### ISSUE TITLE
Less Than or Equal threshold triggers

### ISSUE THREAD

**Issue by EEParker** [grafana/grafana-polystat-panel#46]
Is it possible to do less-than-equal-to thresholds? For example, available RAM on a server. 

I can set up color highlighting with the current method of greater-than-equal-to, but it shows triggered even for the 'good' state since it is the highest numerical value.

**Comment by briangann** [comment]
Can you give a screenshot showing this in a little more detail?

It sounds like a bug in the trigger code vs needing to add operators. The design was to allow "bands" and ranges as triggers.

**Comment by usernkey** [comment]
I see the same I want the number change color when is less then 2 (yellow) or less then 1 (red).
<img width="1612" alt="Screenshot 2020-06-26 at 10 41 06" src="https://user-images.githubusercontent.com/12896983/85838339-ba32eb80-b799-11ea-85c6-50f5d06fbc44.png">

**Comment by usernkey** [comment]
I used this workaround
<img width="1632" alt="Screenshot 2020-06-26 at 10 46 15" src="https://user-images.githubusercontent.com/12896983/85838785-61178780-b79a-11ea-9c00-2c3aaddc7e1a.png">
<img width="1634" alt="Screenshot 2020-06-26 at 10 46 31" src="https://user-images.githubusercontent.com/12896983/85838796-6379e180-b79a-11ea-8b72-4b9fdb167756.png">
