### ISSUE TITLE
Minor improvements : text-color and multiple line labels

### ISSUE THREAD

**Issue by murvoy** [grafana/grafana-polystat-panel#49]
Hi,

Thanks for a great plugin! Would it be possible to:

* add a setting to control the color of the text inside each cell,
* have the ability to insert line breaks into the text label?

Thanks again,
Matthieu

**Comment by briangann** [comment]
The line breaks are something I'd like to add. Since this is rendered via D3, it's tough to make a multi-line label.

For the first item (control color) - Sounds like that needs to be a global setting, an override option (and per-threshold?), plus composite.

**Comment by murvoy** [comment]
Hi Briangann,

Thanks for the reply, happy to see that you may be interested in making these improvements :-)

Regarding the line break, I have no idea how this is rendered with D3, but this would clearly help w.r.t. to the readability of texts when these are a bit too long to fit the hexagon width.

Regarding the text color, yes, being able to specify per threshold both the background color of the hexagon (already the case) and the inner text color would be a nice addition.
When using rather dark colors, the current default black is sometimes difficult to read.

Cheers,
Matthieu

**Comment by briangann** [comment]
adding this to the backlog, some reworking of the layout is in progress right now and we may be able to include this in the PR

**Comment by techcubs** [comment]
+1

**Comment by eti** [comment]
Hi, I'm very much interested in this feature - 'multiline labels'.
[Here ](https://bl.ocks.org/guypursey/f47d8cd11a8ff24854305505dbbd8c07) is the link how it can be done in d3.js

**Comment by jordanmat** [comment]
Multi-line label feature would be great.
