### ISSUE TITLE
Feature Request: allow wildcards in Override section

### ISSUE THREAD

**Issue by andrewmeyer** [grafana/grafana-polystat-panel#51]
I am looking to create thresholds for a group of similar metrics and it looks like this is done by creating an override.  Unfortunately it does not appear that overrides use wildcards when matching metrics.  Creating an override per metric (in this case fan speeds) with identical thresholds is not very salable.

A default set of thresholds might also be nice to have.  This way we can override metrics that require a different warm/crit value.

I am currently running Polystat 1.0.16 on Grafana v6.1.1 (commit: eff01d2)

**Comment by briangann** [comment]
Overrides will accept regex-type matches.  I use it similarly for fan speeds and temperatures.

![image](https://user-images.githubusercontent.com/7364245/55739637-0c4dec80-59ef-11e9-995e-d5f9b57a61fb.png)

Can you show a screenshot of your override setting and what it is doing?

**Comment by andrewmeyer** [comment]
I was using Grafana-style regex as opposed to regexp.  This is working now.
