### ISSUE TITLE
tooltip should contain the name of the Composites

### ISSUE THREAD

**Issue by yarix** [grafana/grafana-polystat-panel#52]
when using composites, the name of the composite should be on the tooltip. 
in many cases, the polygon can't show the title of the composite, it will be great to have it at least in the toolip

![image](https://user-images.githubusercontent.com/6409857/56658710-fc4b3380-66a3-11e9-8ec9-0c0954c02382.png)
,

**Comment by briangann** [comment]
this is a great feature addition - the built-in tooltip component may need to be extended to support it

**Comment by yarix** [comment]
thank you :)
