### ISSUE TITLE
[FR] Adding "Open in new tab" functionality for the clickThroughUrl setting

### ISSUE THREAD

**Issue by adivinho** [grafana/grafana-polystat-panel#55]
It would be very useful to have a possibility of opening pages in a new tab.
As it's done in the Graph panel.

![Screenshot_20190524_155619](https://user-images.githubusercontent.com/25184101/58329483-507d3b00-7e3d-11e9-9358-c5a685441c7c.png)

**Comment by matletix** [comment]
Looks like it got implemented in #64. @briangann @adivinho should we close this ?
