### ISSUE TITLE
[Bug] Legends and Values are not clickable

### ISSUE THREAD

**Issue by adivinho** [grafana/grafana-polystat-panel#56]
It's not possible to click on a hexagon if mouse cursor is placed over a legend or value.
Links are only working if a tooltip is shown.

Panel version: 1.0.16
Browser: Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)

![Screenshot_20190524_162416](https://user-images.githubusercontent.com/25184101/58330870-82dc6780-7e40-11e9-86d6-7de0eda1c8e9.png)

**Comment by briangann** [comment]
this was fixed - the tooltip is offset from the mouse to prevent it from covering the polygon
