### ISSUE TITLE
Multiple variables cannot be passed into clickThrough url

### ISSUE THREAD

**Issue by polasekr** [grafana/grafana-polystat-panel#58]
I am passing multiple parameters into clickThrough url. Specifically I am trying to pass the variable $service from the dashboard and the cell name that represent name of the specific container. 
This is my clickThrough url I defined:

dashboard/db/docker-host-and-container-overview?var-containergroup=${__cell_name}&var-service=$service used for repeating panels 

It appears that url string is being passed through $sanitize function which converts "&" symbols into &amp; when sanitize switch is turned on. 

The resulting url is:
/d/K5E5flWWz/docker-host-and-container-overview?orgId=1&var-containergroup=apps&amp;var-service=All.

If sanitize switch is turned off, the clickThrough is not working at all.

I am also noticing, that variable $service is not being replaced with the value for the actual panel, but with value "All"

**Comment by adivinho** [comment]
Here are some screenshots refer the "&" symbol converting

![Screenshot_20190605_094742](https://user-images.githubusercontent.com/25184101/58939558-25211700-8780-11e9-9b48-ca7d6be909c1.png)

![Screenshot_20190605_094832](https://user-images.githubusercontent.com/25184101/58939562-27837100-8780-11e9-9e82-f1bd00bcda01.png)

**Comment by matletix** [comment]
Looks like it got implemented in #64. @briangann @polasekr should we close this ?

**Comment by polasekr** [comment]
Yes, lets close it. Thank you for the fix.
