### ISSUE TITLE
Add input for display label in override

### ISSUE THREAD

**Issue by mielverkerken** [grafana/grafana-polystat-panel#59]
- A common pattern to create composites is to give the metric a prefix to make the composite on.

- Example:
Metrics `SERVER_cpu`, `SERVER_memory`, ... will be put in one composites with a name `SERVER` and regex` SERVER.*`. Resulting in a bucket for each server with all their metrics, great! 
Only thing that is bugging me is that the tooltip now consist of `SERVER_cpu`, `SERVER_memory` ... , the prefix SERVER is now redundant as it is already in the composite SERVER.

- Proposed Solution:
Add a input field for a display label to a override so this can be used as label in the panel.
Than you could configure the display label for `SERVER_cpu` as `cpu`.

**Comment by briangann** [comment]
very useful feature, adding to backlog :)
