### ISSUE TITLE
Singlestat panel value is shown over Polystat tooltip

### ISSUE THREAD

**Issue by ulikl** [grafana/grafana-polystat-panel#61]
**What happened**:

When combining Singlestat and Polystat panels and the Polystat tooltip overlaps with the Singlesstat text, the SingleStat panel value is shown on top. So not all data of the tooltip can be seen.
E.g.
![SingleStatText_over_PolystatTooltip](https://user-images.githubusercontent.com/40604083/60009831-d972d680-9676-11e9-848e-7a183279a771.png)

I already opened this as Grafana issue in https://github.com/grafana/grafana/issues/17610. But it was referred to this polystat repository.

Additionally I have seen that the info triangle (i) of other panels is also shown above the polystat tooltip.

**What you expected to happen**:

I expect the tooltip to be shown also on top of all other overlapped panels.
This does for example not happen with the Polystat tooltip overlapping panels from the plugins Graph and natel-discrete-panel.

**How to reproduce it (as minimally and precisely as possible)**:

I can produce it with this simple dashboard using a Prometheus datasource with basic metrics:
[SingleStatText_over_PolystatTooltip_json.txt](https://github.com/grafana/grafana-polystat-panel/files/3320218/SingleStatText_over_PolystatTooltip_json.txt)

**Anything else we need to know?**:
  None.

**Environment**:
- Grafana version: 6.2.2 

- Data source type & version:
   reproduced with Prometheus and InfluxDB (preinstalled plugin from Grafana version )

- OS Grafana is installed on:
  Grafana docker image grafana/grafana:6.2.2

- User OS & Browser:
  Firefox 67.0.1
  Windows 10

- Grafana plugins:
   Polystat 1.0.16
   SingleStat preinstalled from grafana 6.2.2 (no version number shown)

- Others:
  None.

**Comment by w4rgrum** [comment]
After some tests, when SingleStat value is displayed alone (no gauge), it has a z-index of 1, this should not be the case, thus you should reopen an issue to SingleStat for that.

Without PolyStat tooltip:
![image](https://user-images.githubusercontent.com/54102154/63950947-3460e980-ca7d-11e9-9ebf-366599997efd.png)

With PolyStat tooltip:
![image](https://user-images.githubusercontent.com/54102154/63950850-08ddff00-ca7d-11e9-9909-049065e438df.png)

PolyStat tooltip over SingleStat with gauge:
![image](https://user-images.githubusercontent.com/54102154/63951064-62dec480-ca7d-11e9-9bcc-617d6b553609.png)

Regarding PolyStat, the z-index of the tooltip is not set (or too low), so there are other issues, for example with the "i" icon of the panels when a description is available. Thus a fix in PolyStat is also required (setting z-index to 2 for example). I will submit a PR for that.

**Comment by ryantxu** [comment]
closed with #87
