### ISSUE TITLE
Auto Size option for Rows and Columns not always displaying all the hexagons

### ISSUE THREAD

**Issue by w4rgrum** [grafana/grafana-polystat-panel#65]
I have a panel where 10 hexagons should be displayed, with Auto Size activated on Rows and Columns I got:

![image](https://user-images.githubusercontent.com/54102154/63700411-26b02780-c823-11e9-815a-71d6e885a856.png)

Expected panel is:

![image](https://user-images.githubusercontent.com/54102154/63700441-37609d80-c823-11e9-97aa-de0623b1288b.png)

**Comment by briangann** [comment]
this should be fixed in the next release, keeping open for verification
