### ISSUE TITLE
Question - Is it possible to show two stats in the same polygon?

### ISSUE THREAD

**Issue by orena1** [grafana/grafana-polystat-panel#72]
Hi, is it possible to show two stats in the same ploygon?
For example 
![image](https://user-images.githubusercontent.com/8983713/68236518-fbf60280-000d-11ea-8789-6d2328d5f130.png)

Thanks

**Comment by luiz-idwall** [comment]
+1

**Comment by briangann** [comment]
yes, if you configure a "composite" it will display each stat in the polygon.

There are options on how they are displayed:

- Show all
- Show triggered (only shows metrics that are outside of "normal")

The tooltip can also be configured to show all/show triggered, and also has sorting options.

**Comment by orena1** [comment]
Thnks, but I did not manage to see something like that. The data is shown in the tooltip, but on the poly itself I can only see one metric
