### ISSUE TITLE
Error after upgrading to 6.5

### ISSUE THREAD

**Issue by mkl262** [grafana/grafana-polystat-panel#74]
Hi,
I upgraded grafana to 6.5.0, and after that the pannel appears empty with the error:
`Cannot read property 'replaceWithText' of undefined`

**Comment by marefr** [comment]
Repro https://play.grafana.org/d/oDa-tExWz/repro-gh-20662?tab=queries&orgId=1&fullscreen&edit&panelId=2

**Comment by marefr** [comment]
Where currently investigating this at https://github.com/grafana/grafana/issues/20662

**Comment by mkl262** [comment]
Issue solved with grafana 6.5.1
