### ISSUE TITLE
Enable value to text mapping 

### ISSUE THREAD

**Issue by infa-kparida** [grafana/grafana-polystat-panel#79]
Is it possible to map text to value in override settings ? 
I am trying to create a dashboard to get service health and need to convert values like 0-Up 1-Down etc.This makes dashboards look good in stead of showing service A -1 Service B -0

**Comment by briangann** [comment]
this is a feature we need to implement, and would likely need to be in both a "global" section and in overrides.

**Comment by IPZAaron** [comment]
Seems to be a duplicate of #42 

I wholeheartedly agree with this one, though. It'd really take this to the next level.
