### ISSUE TITLE
convert to use dataframes

### ISSUE THREAD

**Issue by briangann** [grafana/grafana-polystat-panel#97]
We need to convert this plugin to use dataframes for easier maintenance and to get table data support.

Recent plugin changes have locked the plugin to v6+, and dataframes are available by default.

**Comment by kylebrandt** [comment]
Oh I didn't see this when I created https://github.com/grafana/grafana-polystat-panel/issues/143 , that has some more information in it, and I closed a Grafana issue pointing to that, so maybe we can close this one @briangann ?
